### ISSUE TITLE
Snapshot build issue

### ISSUE THREAD

**Issue by rorygraves** [scoverage/sbt-scoverage#100]
Hello,

I was trying to publish local the various snapshot versions so I could test some of the recent project aggregation fixes.  However I get into a nasty state and was wondering if I was missing something obvious.  So I:

Step 1:  PublishLocal scalac-scoverage-plugin

```
[info]  published scalac-scoverage-plugin_2.11 to /home/rory/.ivy2/local/org.scoverage/scalac-scoverage-plugin_2.11/1.0.5-SNAPSHOT/poms/scalac-scoverage-plugin_2.11.pom
[info]  published scalac-scoverage-plugin_2.11 to /home/rory/.ivy2/local/org.scoverage/scalac-scoverage-plugin_2.11/1.0.5-SNAPSHOT/jars/scalac-scoverage-plugin_2.11.jar
```

Step 2: PublishLocal sbt-scoverage

```
[info]  published sbt-scoverage to /home/rory/.ivy2/local/org.scoverage/sbt-scoverage/scala_2.10/sbt_0.13/1.0.5-SNAPSHOT/jars/sbt-scoverage.jar
```

Step 3-  attempt to compile my project against plugin 1.0.5-SNAPSHOT

```
[warn]  Note: Unresolved dependencies path:
[warn]          org.scoverage:scalac-scoverage-plugin_2.10:1.0.5-SNAPSHOT
[warn]            +- org.scoverage:sbt-scoverage:1.0.5-SNAPSHOT (sbtVersion=0.13, scalaVersion=2.10) (/home/rory/workspace/ensime-server/project/plugins.sbt#L6-7)
[warn]            +- default:ensime-server-build:0.1-SNAPSHOT (sbtVersion=0.13, scalaVersion=2.10)
```

I'm guessing the4 sbt-scoverage cannot depend on a 2.11 scalac-scoverage (as sbt is 2.10).  I'm guessing the dependency is to that is pulled in to be added to the compiler path for the coverage run.

@gslowikowski @sksamuel  Am I missing something obvious in my testing? - I can see you have done a whole load of work in the area - I accept that I might be showing my lack of knowledge around the joys of sbt plugins.

Cheers

Rory

**Comment by gslowikowski** [comment]
Hi Rory

You should publish `scalac-scoverage-plugin` with `sbt +publishLocal`. It will publish both 2.10 and 2.11 versions. `sbt-scoverage` needs `sbt publishLocal` (without the plus sign).

I've published `scalac-scoverage-plugin` 1.0.5-SNAPSHOT to Sonatype snapshots repository, and would like to publish snapshots regularly (to be discussed with @sksamuel). To resolve it you have to add `Resolver.sonatypeRepo("snapshots")` resolver to your build.

Now I we have some problems with `sbt-scoverage` snapshot publishing (it was never published as a snapshot before and SBT snapshots have their own specific repository).

I see your recent activity and wanted to discuss with you how to use my recent changes related to multiple source roots in single- and multi-module projects. We can do it here if you wish.

**Comment by sksamuel** [comment]
1.0.5-SNAPSHOT is now available on sbt plugin snapshots.

**Comment by rorygraves** [comment]
Awesome stuff.  @gslowikowski yep, will to discuss any of it online or offline - I'm not going to claim expertise, just willingness though.  We could alway setup travis to publish the snapshots.

**Comment by rorygraves** [comment]
@sksamuel @gslowikowski The 1.0.5-SNAPSHOT looks good - but mutlimodule builds with sbt-coveralls are broken in combination - looks like the package names are missing from a path - will try and address that tomorrow.  The 1.0.5-SNAPSHOT reports and multi-module stuff looks great.

**Comment by gslowikowski** [comment]
Any results?

**Comment by rorygraves** [comment]
@gslowikowski Sorry, been slow on this - I think we should go ahead and push a version now (it addresses some bugs) and I dont think it introduces a regression.  I can then  another PR if I see more problems with multimodule with the ```scalac-scoverage-plugin```

**Comment by fommil** [comment]
@rorygraves @gslowikowski what's the status on the release? We haven't had coverage reports for almost two months now :cry:

**Comment by gslowikowski** [comment]
Remind me, why you cannot use scoverage 1.0.4?

**Comment by fommil** [comment]
one for rory

**Comment by sksamuel** [comment]
@rorygraves one for rory apparently :)

**Comment by aragnon** [comment]
@gslowikowski What is the difference between `sbt +publishLocal` and `sbt publishLocal`?

**Comment by gslowikowski** [comment]
`+` sign means publishing for all Scala versions in `crossScalaVersions`

**Comment by ckipp01** [comment]
This should be taken care of now. If there are any issues related to this, please do report back.
