### ISSUE TITLE
java.io.FileNotFoundException when copying source code file from src_managed

### ISSUE THREAD

**Issue by brliujerry** [scoverage/sbt-scoverage#103]
It looks like scoverage is not able to copy generated source code from target/.../src_managed.

**Comment by gslowikowski** [comment]
You have to `1.0.5-SNAPSHOT` version. Previous versions support only `src/main/scala` sources.

**Comment by brliujerry** [comment]
Thanks.

**Comment by ckipp01** [comment]
I believe this should be fixed now. If not, feel free to report back.
