### ISSUE TITLE
scala 2.11.4 libraries added to classpath when using scoverage-sbt

### ISSUE THREAD

**Issue by fommil** [scoverage/sbt-scoverage#106]
If I add

```scala
addSbtPlugin("org.scoverage" %% "sbt-scoverage" % "1.1.0")
```

to my projects (e.g. `ensime-server`) then sbt is adding various scala 2.11.4 libraries to my classpath, even though I already have 2.11.6.

This happens with caching either on or off.

To reproduce, type `sbt gen-ensime` and inspect the `.ensime` file that is produced.

**Comment by fommil** [comment]
ping, is anyone looking into this?

It looks like these lines may be the culprits https://github.com/scoverage/sbt-scoverage/blob/master/src/main/scala/scoverage/ScoverageSbtPlugin.scala#L93

These should probably be marked `intransitive()`

**Comment by sksamuel** [comment]
You'd think that provided dependencies wouldn't bring in anything else. If you're right, then its a bug with SBT in my opinion. (other than sbt being a big bug haha, I'll get my coat). We can add your suggestion to work around it.

**Comment by fommil** [comment]
Don't get me started on SBT. I was recording our ENSIME demo for Scala days and near 50% of the time was waiting for SBT to finish fscking resolving files it had already downloaded.

**Comment by sksamuel** [comment]
There's no bugs left in the scala compiler, nor any features anyone wants.
So it's good economical sense to put two of your best developers onto a
build tool no one likes.

**Comment by fommil** [comment]
And have them work on things that nobody cares about. Screw performance and integration with corporate environments!

**Comment by sksamuel** [comment]
There's nothing wrong with resolving the same dependency 100 times per
module.

**Comment by sksamuel** [comment]
I switched us over to gradle at work and haven't looked back. If gradle had
a cross build like sbt I'd move all my open source projects too.

**Comment by fommil** [comment]
Can't you set Scala version with an environment variable? Does it do incremental compilation?

**Comment by sksamuel** [comment]
No idea.

**Comment by fommil** [comment]
ok, sticking `intransitive()` on the end of those two lines seems to fix the problem. I'd send you a PR but it looks like your `master` is trailing your 1.1.0 release. Can you pretty please make that change and issue a 1.1.1 update?

**Comment by fommil** [comment]
btw, are you sure you need to add both jars to the project's classpath for it to work? Seems excessive. I thought it was more important to have the jar on the compiler's classpath.

**Comment by fommil** [comment]
@sksamuel ping! BTW, we'll be giving you a shout out at scaladays... the ENSIME talk has a slide with coveralls on it and (unless I get nervous and forget) I'll be sure to let everyone know we're using scoverage for it.

**Comment by sksamuel** [comment]
I'll sort this for you soon :)

**Comment by fommil** [comment]
:smile:

**Comment by fommil** [comment]
great! Do you have a 1.1.1 release planned?

**Comment by sksamuel** [comment]
Yep, today.

**Comment by gslowikowski** [comment]
See my comments here: https://github.com/scoverage/sbt-scoverage/commit/4af7a7af3d7f60a4b73e57ae954fce2b5b30baa0

**Comment by sksamuel** [comment]
The plugin is needed on the classpath as it also contains the code for generating the reports and things like that. It's more than just the scalac compiler plugin code. It could be separated out, but then we'd need a common "domain" module between the new "reporter" module and the scalac plugin. Then people will need to upgrade the gradle, sbt and maven deps.

Seems like a bit of work for nothing, since the deps are tiny anyway. This change in this issue will stop all the other stuff coming down with it.

**Comment by sksamuel** [comment]
1.2.0 released

**Comment by gslowikowski** [comment]
That's not what I mean. You could get `scalac-scoverage-plugin` dependency artifact from plugin's dependencies (https://github.com/scoverage/sbt-scoverage/blob/1.2.0/build.sbt#L19) somehow, instead of getting it from project's dependencies here: https://github.com/scoverage/sbt-scoverage/blob/1.2.0/src/main/scala/scoverage/ScoverageSbtPlugin.scala#L104.

I know, how to do it in Maven, but cannot find a way in SBT.

**Comment by sksamuel** [comment]
It's different classpaths. The former is the classpath for the project
files, the latter is the classpath for the compiler itself.

**Comment by gslowikowski** [comment]
Of course they are.

**Comment by fommil** [comment]
The lines affected by this commit are the project, not the compiler. Or are they one and the same in SBT?

**Comment by gslowikowski** [comment]
No. Never mind.
