### ISSUE TITLE
no scoverage instrumentation output

### ISSUE THREAD

**Issue by cbismuth** [scoverage/sbt-scoverage#107]
Project: https://github.com/cbismuth/scala-for-the-impatient
Build command: `sbt clean coverage test`

Here is my SBT [plugin.sbt](https://github.com/cbismuth/scala-for-the-impatient/blob/master/project/plugins.sbt) file wich depends on sbt-scoverage 1.1.0.

Output tells:

```
[info] Reading scoverage instrumentation [/home/chris/Work/git/public/scala-for-the-impatient/target/scala-2.11/scoverage-data/scoverage.coverage.xml]
[info] Run completed in 2 seconds, 291 milliseconds.
[info] Total number of tests run: 124
[info] Suites: completed 63, aborted 0
[info] Tests: succeeded 124, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 31 s, completed May 15, 2015 4:38:06 PM
```

But file `target/scala-2.11/scoverage-data/scoverage.coverage.xml` doesn't exist.

**Comment by gslowikowski** [comment]
Hi
In your project you have no main classes, only tests. No classes -> no coverage data.

**Comment by cbismuth** [comment]
Thank you @gslowikowski for quickly answering my question! :+1:

**Comment by cbismuth** [comment]
I still can't get my coverage data displayed in Codacy dashboard, but they told me there's an issue with sbt-codacy-coverage plugin, they are working on it.
@gslowikowski you can close this issue, thank you.
