### ISSUE TITLE
Turning coverage on in the console can't be turned off

### ISSUE THREAD

**Issue by gregsymons** [scoverage/sbt-scoverage#109]
Once you turn on coverage in a given sbt session, it can't be turned off. I thought of adding a `nocoverage` task, but then I wondered if the truly correct solution would be to make `enabled` a Setting rather than the var it currently is. What do you think?

**Comment by sksamuel** [comment]
You mean once you've done sbt coverage, subsequent calls to sbt test produce output? If so, do a sbt clean compile and it should be gone.

**Comment by gregsymons** [comment]
No, I mean if I'm running an sbt console (i.e. I run `sbt` with no task), if I execute the `coverage` task in that console session, then from that point on, compiling generates instrumented classes.

**Comment by sksamuel** [comment]
Ah right. That's because it sets a variable. I think we could add a
"coverageoff" one that does the opposite.

**Comment by gregsymons** [comment]
Yep. I just wanted to see what your opinion on fixing it was before I dove in and did it. I'll go ahead and add `coverageoff` task and have a PR ready shortly.

**Comment by sksamuel** [comment]
1.2.0 released.
