### ISSUE TITLE
coverage of entire project

### ISSUE THREAD

**Issue by fommil** [scoverage/sbt-scoverage#112]
It looks like the coverage report for a module is only gathered for tests run in that module.

I'd like to be able to see the coverage of my entire (multi module) project when I run some integration tests... to see what I can delete :smile: ... is that possible?

**Comment by sksamuel** [comment]
The `sbt coverageAggregate` functionality is meant to cover that.

**Comment by fommil** [comment]
Hmm, it not sure it does that. I'm seeing 0% coverage outside my top level module

**Comment by fommil** [comment]
yeah, `coverageAggregate` definitely doesn't do what I'm asking. It seems to just join reports together. If I have a project with modules A and B, B depends on A, A doesn't have any tests, B has tests that exercise the entire codebase (including everything in A), then a `coverageAggregate` will show 0% coverage for module A.

**Comment by sksamuel** [comment]
So your tests for A are actually part of B. Then yeah that wouldn't work.
That's like you writing unit tests for scala.collection and wanting code
coverage for that.

**Comment by fommil** [comment]
Yeah, kind of. The point is that I have integration tests (which live in B) and I want to see what parts of the code are dead across the project.

**Comment by sksamuel** [comment]
I guess it could be done. Worst case is you could do

sbt compile
sbt test

as two separate things that would result in the profile data. Then

sbt report (or something)

to clean up after.

**Comment by RichardBradley** [comment]
Does this workaround fix your case?
https://github.com/scoverage/sbt-scoverage/issues/87#issuecomment-130618860

**Comment by RichardBradley** [comment]
I'm using ver 1.3.1 to produce coverage reports where some of the tests in project A cover classes in project B and it's working well for me.
