### ISSUE TITLE
Scoverage test for Scala compiler failed

### ISSUE THREAD

**Issue by XinyuHua** [scoverage/sbt-scoverage#116]
I am trying to use scoverage to test scala compiler, which I built from source by sbt. 

At first when I didn't add "addSbtPlugin(...)" to my /project/plugins.sbt it worked all fine, both sbt compile and sbt test. But when I added that and run "sbt clean coverage test", it shows error:

[error](library/compile:compile) java.lang.ClassCastException: xsbt.API$ApiPhase cannot be cast to scala.tools.nsc.Global$GlobalPhase

I am using sbt version 0.13.7

Thanks in advance for any comments!

**Comment by ckipp01** [comment]
I want to assume that this is no longer an issue. If you still do have this issue, please do report back.
