### ISSUE TITLE
Any chance at a way to combine sub-project reports into one?

### ISSUE THREAD

**Issue by agemooij** [scoverage/sbt-scoverage#13]
I've just started using the sbt-scoverage plugin and my first impression is that it is much better than jacoco or scct. Great work!

My current project has multiple sub-projects and I was wondering whether you see a way to combine the outputs of all the individual tests into one big report across all projects. Do you think this is possible?

I'm more than willing to help add this feature. At this point I'm just not sure how hard/easy it would be and where to start.

Again, great work!
Age

**Comment by deepujain** [comment]
I have a maven project and not sbt, how do i get a aggregated scoverage report for my project that has multiple modules. I see that each individual module creates a scoverage.xml in its target directory.

Currently from top-level i run it as mvn clean test install scoverage:report -Dmaven.test.failure.ignore=true

**Comment by FelixReuthlingerBMW** [comment]
I was also wondering if there is any chance that the Maven plugin get updated with the aggregate feature, too?
