### ISSUE TITLE
Wrong artifact published. Label is 1.3.1, source is 1.1.1

### ISSUE THREAD

**Issue by akara** [scoverage/sbt-scoverage#135]
Using the latest scoverage 1.3.1, I found that multi-project coverage is not working properly. This is despite the fix https://github.com/scoverage/sbt-scoverage/commit/9642a98f5a99abe138d012079df3bd457635cff7 being in place. Further investigation by downloading the source jar from https://dl.bintray.com/sksamuel/sbt-plugins/org.scoverage/sbt-scoverage/scala_2.10/sbt_0.13/1.3.1/srcs/ shows this code:

```
  val ScoverageVersion = "1.1.1"
```

and toggleCoverage implementation still being the old, before the commit above. So it seems clearly that the 1.1.1 code has been published as 1.3.1 and the fixes are definitely not in place. The fix could be somewhere in your build process. Thanks!

**Comment by mirkof** [comment]
++

**Comment by saurfang** [comment]
It looks like `ScoverageVersion` was never bumped anyway. https://github.com/scoverage/sbt-scoverage/blob/master/src/main/scala/scoverage/ScoverageSbtPlugin.scala#L12

But yes I'm having the same problem that I don't see the multiproject fix in 1.3.1 source. Looks like 1.3.1 and 1.3.0 srcs are identical.

**Comment by akara** [comment]
Yup, you're right, checking back at the commit the value was never bumped in the code. But most importantly, the toggleCoverage fix in the commit above is not in.

**Comment by sksamuel** [comment]
1.3.2 is released with the fixes. This release is on maven central on bintray.

**Comment by sksamuel** [comment]
@akara @saurfang  @mirkof thanks for reporting issue and sorry for delay
