### ISSUE TITLE
Publish Snapshots

### ISSUE THREAD

**Issue by m-sp** [scoverage/sbt-scoverage#144]
I wanted to try out the teamcity support (#140) according to the build.sbt snapshots are configured to be published at https://oss.sonatype.org/content/repositories/snapshots/org/scoverage/ but i can't find the sbt plugin there.
Would it be possible to automatically publish snapshots?

**Comment by sjoerdmulder** [comment]
same here, could you maybe publish a new release?

**Comment by rumoku** [comment]
+1

**Comment by dk14** [comment]
+1

**Comment by sksamuel** [comment]
I can do a release from master tonight to maven central.

**Comment by dk14** [comment]
cool! :)

**Comment by rumoku** [comment]
Hi, I can not find new version in maven central. Thx.

**Comment by sksamuel** [comment]
1.3.4 is now released. Thanks all.

**Comment by m-sp** [comment]
thank you very much @sksamuel, will try the new version in the next couple of days!
for my purpose i consider this issue fixed, so feel free to close this!

**Comment by gslowikowski** [comment]
What is this https://github.com/scoverage/sbt-scoverage/blob/v1.3.4/src/main/scala/scoverage/ScoverageSbtPlugin.scala#L13?

There is no `1.2.0` version. Travis build fails since about a month (https://travis-ci.org/scoverage/sbt-scoverage/builds). Nobody cares?

**Comment by rumoku** [comment]
I've updated to 1.3.4, but build now my fails:
[error] (common-test/*:update) sbt.ResolveException: unresolved dependency: org.scoverage#scalac-scoverage-runtime_2.11;1.2.0: not found
[error] unresolved dependency: org.scoverage#scalac-scoverage-plugin_2.11;1.2.0: not found
[error] Total time: 97 s, completed Jan 7, 2016 10:03:21 AM


Should issue be reopened?

**Comment by sksamuel** [comment]
Should be, I'm going to release 1.3.5 now that will fix that.

**Comment by sksamuel** [comment]
Give 1.3.5 a go.

**Comment by rumoku** [comment]
Hi, 
Tested 1.3.5. It works good. 
TeamCity collects all necessary statistics.

Thank you!
