### ISSUE TITLE
Version 1.3.3 available in mavencetral/bintray/etc

### ISSUE THREAD

**Issue by thomaska** [scoverage/sbt-scoverage#145]
Hi,

Is version 1.3.3 available in any central repo?
I checked in <a href="https://dl.bintray.com/sksamuel/sbt-plugins/">https://dl.bintray.com/sksamuel/sbt-plugins/</a> but I only found up until 1.3.1.

This is more like a question rather than an issue, but i didn't know anywhere else to post it.

Thank you,
Thomas

**Comment by sksamuel** [comment]
Yeah its in maven central. I can't get bintray to sync properly, so might as well use maven central.
http://search.maven.org/#search|ga|1|sbt-scoverage

**Comment by thomaska** [comment]
Could you please verify that it has been is uploaded correctly?
When I visit <a href="https://repo1.maven.org/maven2/org/scoverage/sbt-scoverage/1.3.3/sbt-scoverage-1.3.3.jar">https://repo1.maven.org/maven2/org/scoverage/sbt-scoverage/1.3.3/sbt-scoverage-1.3.3.jar</a> <br> I get a 404 and when I try to include it in my project I get version 1.1.1 (as it appears in list of external libraries in IntelliJ.
Thank you.

**Comment by gslowikowski** [comment]
SBT plugins have specific names, with Scala and SBT versions as suffixes. See:
https://repo1.maven.org/maven2/org/scoverage/sbt-scoverage_2.10_0.13/1.3.3/
