### ISSUE TITLE
Unable to enable coverage in a multiproject build via non-interactive sbt

### ISSUE THREAD

**Issue by brettcave** [scoverage/sbt-scoverage#147]
In a multiproject build, I want to enable coverage for a custom configuration in a specific project. I am able to do this easily in a SBT console:

```
$ sbt
sbt (baseproject) > project multimodule-x
sbt (multimodule-x)> clean
sbt (multimodule-x)> coverage
sbt (multimodule-x)> unit:test
sbt (multimodule-x)> coverageReport
...
[info] Coverage reports completed.
```

Unit test is a config that extends Test. This generates coverage reports. However, if I run the following, code is not instrumented (i've tried both base module `coverage` and project-specific `coverageEnabled` in the example below)

```
$ sbt clean coverage multimodule-x/coverageEnabled multimodule-x/unit:test
$ sbt multimodule-x/coverageReport
[warn] No coverage data, skipping reports
```

**Comment by brettcave** [comment]
Wanting to do this for a build system, seperating covered and non-covered testing - so `coverageEnabled := true` in build.sbt is not an option.

**Comment by FeetInAncientTime** [comment]
I'm experiencing exactly the same problem with the following versions of SBT and Scoverage:
- SBT 0.13.9
- Scoverage 1.3.1
I'm not able to use a later version of Scoverage for the moment.

**Comment by Raffaello** [comment]
Any updates on this issue?

I am experiencing the same with:

- SBT 1.1.6
- Scoverage 1.5.1

**Comment by ckipp01** [comment]
You should be able to simple do `sbt coverage module/test coverageReport`. Since this is quite old I'm going to go ahead and close. If that doesn't solve your issue, please do comment back or open back up.
