### ISSUE TITLE
Cannot update driver for postgresql

### ISSUE THREAD

**Issue by jlin-program** [scoverage/sbt-scoverage#157]
I am running into 

    `[error] (*:update) sbt.ResolveException: unresolved dependency: postgresql#postgresql;9.4-1206-jdbc42: not found`

when running `activator run`

Here is my `build.sbt`

```
libraryDependencies ++= Seq(
  jdbc,
  cache,
  ws,
  specs2 % Test,
  "postgresql" % "postgresql" % "9.4-1206-jdbc42",
  "org.xerial" % "sqlite-jdbc" % "3.7.15-M1"

)

resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"
resolvers += "Typesafe Public Repo" at "http://repo.typesafe.com/typesafe/releases"
resolvers += Resolver.url("Typesafe Ivy releases", url("https://repo.typesafe.com/typesafe/ivy-releases"))(Resolver.ivyStylePatterns)
resolvers += Resolver.url("scoverage-bintray", url("https://dl.bintray.com/sksamuel/sbt-plugins/"))(Resolver.ivyStylePatterns)


```

I tried adding multiple resolvers, but all resulted in the same error.

Any help would be appreciated

Thanks

**Comment by gslowikowski** [comment]
Should be `"org.postgresql" % "postgresql" % "9.4-1206-jdbc42"`. This issue has nothing to do with Scoverage, right?

**Comment by jltqst100** [comment]
Yeah, just realize I post on the wrong repository, was opening too much tab on my chrome, please close this for now.

Thanks
