### ISSUE TITLE
Scala version specific tests included in coverage report.

### ISSUE THREAD

**Issue by everson** [scoverage/sbt-scoverage#160]
In a project with scala 2.11 specific code and tests, the tests get included as part of the main source

Example of report: https://codecov.io/github/khronnuz/shapeless?ref=9a4bc2936bff479547e4cd2bcfbf52c9a78ad163&view=all

There are occurrences of `src/test/scala_2.11+/shapeless/singletons.scala`

**Comment by ckipp01** [comment]
Due to how old this is I'm going to go ahead and close. If you still do have any issues with this, please do report back.
