### ISSUE TITLE
coverageAggregate don't find subprojects

### ISSUE THREAD

**Issue by catena2w** [scoverage/sbt-scoverage#170]
I'm trying to build aggregate report for https://github.com/ScorexProject/Scorex project. I run commands:

`sbt clean coverage test`
`sbt coverage test`

After that I see all coverage data in `target` directories. I can also build report for each subproject separately, e.g. `sbt "project basics" "coverageReport"` creates good report for `basics` subproject.
Now I want to create aggregated report, I run `sbt coverageAggregate`, but it includes only reports from root project (from `target` folder only, ignoring `scorex-basics/target`, `scorex-transactions/target` etc.).
How to create aggregated report for all of my subprojects?

**Comment by gslowikowski** [comment]
Check [this PR](https://github.com/scoverage/scalac-scoverage-plugin/pull/156).

I can generate aggregated coverage for your project, if I have coverage reports` for at least two files generated before. Can you confirm my observation?

**Comment by gslowikowski** [comment]
Upgrade `sbt-scoverage` plugin to version `1.4.0`
