### ISSUE TITLE
scoverage fails on custom configuration

### ISSUE THREAD

**Issue by fchaillou** [scoverage/sbt-scoverage#178]
Hello,

I have defined a custom e2e test configuration that extends test where we put our end 2 end tests.
Trying to run them with scoverage enabled fails with 
``` 
> sbt coverage e2e:test
 java.lang.ClassNotFoundException: scoverage.Invoker$
```

I guess it fails because the library dependencies are not added to my e2e configurations.
Have you an idea of how to fix it ?
Thanks
Fabien

**Comment by gslowikowski** [comment]
Can you provide test project?

**Comment by fchaillou** [comment]
Hello,
Sorry for the delay.

Here is a test project that shows the issue : https://github.com/fchaillou/sbt-scoverage-issue-178

Thanks !
Fabien

**Comment by gslowikowski** [comment]
Replace
```scala
val End2EndTest = config("e2e") extend Runtime describedAs "End2End testing configuration"
```
with
```scala
val End2EndTest = config("e2e") extend(Runtime, Provided) describedAs "End2End testing configuration"
```

By the way, I think `scalac-scoverage-runtime` should be added inside Scoverage plugin with `runtime` scope, instead of `provided`. But this is a topic for another issue.

**Comment by fchaillou** [comment]
Great, it works.
Just a quick question however.
When i look at test or integration test definition in sbt i see that :
```
  lazy val IntegrationTest = config("it") extend (Runtime)
  lazy val Runtime = config("runtime") extend (Compile)
```

So i'm wondering why scoverage works for those and not for e2e (i guess there is specific settings in the plugin but i didn't check :))

**Comment by gslowikowski** [comment]
Nothing specific.

Loot at:
https://github.com/sbt/sbt/blob/v0.13.12/ivy/src/main/scala/sbt/Configuration.scala#L18
https://github.com/sbt/sbt/blob/v0.13.12/ivy/src/main/scala/sbt/Configuration.scala#L30
https://github.com/sbt/sbt/blob/v0.13.12/ivy/src/main/scala/sbt/Configuration.scala#L21-L27

At line 30 configuration additionally extends Optional and Provided confs.
I don't know, why SBT declares internal configurations (https://github.com/sbt/sbt/blob/v0.13.12/ivy/src/main/scala/sbt/Configuration.scala#L16-L19) and maps to them in `internalMap` method. You can debug SBT, if you want to know more.

**Comment by fchaillou** [comment]
Oh ok, that is pretty weird indeed :)
Thanks for the explanation !
