### ISSUE TITLE
new release with html report bug fix

### ISSUE THREAD

**Issue by ericbroder** [scoverage/sbt-scoverage#180]
Hello, I am having this problem which was fixed here: https://github.com/scoverage/scalac-scoverage-plugin/commit/9ff7e25de0e06836f13518acebbaa29c8173f7db

Can you please publish a new release? Looks like it's already fixed in master?

**Comment by ericbroder** [comment]
I see related issue here: https://github.com/scoverage/scalac-scoverage-plugin/issues/170

**Comment by gslowikowski** [comment]
I'm working on some problems in `sbt-scoverage` now. After they will be fixed, we will perform a release.

**Comment by ericbroder** [comment]
Great, thanks!

**Comment by ericbroder** [comment]
Thanks, this is resolved now.
