### ISSUE TITLE
Can't find both in Sonatype Central and Maven Central

### ISSUE THREAD

**Issue by willypt** [scoverage/sbt-scoverage#190]
It seems that I can't find the sbt-coverage [1.4.0] plugin in both Central. Anyone can give me hint what happened recently? Is it not published yet? Or are you publishing to different repo?

Both repo doesn't have sbt-coverage [1.3.5] or [1.4.0] listed.
```
https://oss.sonatype.org/content/repositories/releases/org/scoverage/
https://repo1.maven.org/maven2/org/scoverage/
```

Also, in the mentioned @sksamuel bintray's, it seems [1.3.5] hasn't published there yet. Is there already another repo for this plugin?
Thanks a lot!

**Comment by gslowikowski** [comment]
https://repo1.maven.org/maven2/org/scoverage/sbt-scoverage_2.10_0.13/

**Comment by willypt** [comment]
Thanks @gslowikowski, I think README.md can now be updated to reflect this change.
