### ISSUE TITLE
Scoverage/Invoker$ NoClassDefFoundError

### ISSUE THREAD

**Issue by samudurand** [scoverage/sbt-scoverage#198]
I have an SBT multi project and when running tests of a subproject individually I get the same error referenced in the old issue #115 

```java.lang.NoClassDefFoundError: scoverage/Invoker$```

I am using version 1.4 . Has a proper solution been found for that issue ?

**Comment by samudurand** [comment]
I solved that issue by adding explicit report coverage in all subproject config instead of on the parent project

**Comment by gslowikowski** [comment]
Can you share test project? I'm not sure, what your project looks like and what commands you call. I'd like to reproduce it myself.
