### ISSUE TITLE
subproject/coverage does not instrument coverage.

### ISSUE THREAD

**Issue by addisonj** [scoverage/sbt-scoverage#205]
I currently have a slightly strange build. It contains a subproject that is NOT aggregated into the root project but does depend on another project:

In other words:

```
lazy val common = (project in file("common"))
  ...

lazy val subOne = (project in file("subOne"))
  .dependsOn(common)
  ...

lazy val subTwo = (project in file("subTwo"))
  .dependsOn(common)
  ...

lazy val root = (project in file("."))
  .dependsOn(common, subOne) // does not depend on subTwo!
```

The problem arises when trying to instrument, when running `sbt subTwo/coverage subTwo/test`,  it fails, because:
```
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: coverage (similar: coverageReport, coverageEnabled, coverageMinimum)
[error] subTwo/coverage
```

If I try and use `subTwo/coverageEnabled` it continues to compile but obviously does instrument. 

It seems like the root cause here is that the alias isn't scoped inside subprojects... not sure if there is a clean way to make that work, but would be nice. My current workaround is to just do `sbt ";set coverageEnabled in ThisBuild := true" subTwo/test`

**Comment by gslowikowski** [comment]
Instead of `sbt subTwo/coverage subTwo/test` you can run `sbt coverage subTwo/test`

**Comment by gslowikowski** [comment]
Did you try my advice? Did it help?

**Comment by gslowikowski** [comment]
I hope I helped.

**Comment by addisonj** [comment]
Hey, sorry for not getting back to you!

Really appreciate the advise but still haven't looked. Will reopen if it
doesn't
