### ISSUE TITLE
Combining results from test and fun:test

### ISSUE THREAD

**Issue by jqno** [scoverage/sbt-scoverage#207]
We have defined a `fun:test` task in SBT, as described [here](http://www.scala-sbt.org/0.13/docs/Testing.html#Custom+test+configuration).

When we run `sbt coverage test fun:test`, we only get the coverage information for either `test` or `fun:test` (depends on which one is run first).

Is there a way to combine these into one report?

**Comment by gslowikowski** [comment]
What plugin version are you using? Since `1.3.4` (latest is `1.5.0`) you need to call `coverageReport` at the end, e.g. `sbt coverage test fun:test coverageReport` and it should work as you expect.

**Comment by jqno** [comment]
I've been using 1.3.5, recently upgraded to 1.5.0, but I see the problem in both versions.

I run `sbt coverage test fun:test`, followed by a separate `sbt coverageReport coverageAggregate`.
(We also have submodules.)

**Comment by gslowikowski** [comment]
Can you prepare simple test project?

**Comment by jqno** [comment]
I've been trying to prepare such a project, but I'm not succeeding. A simple dummy project with some submodules and separated tests just works. (You can see it here: https://github.com/jqno/scoverage-issue )

Our build has some idiosyncracies (being written and grown over time by people who are not SBT experts, you probably know what that's like) so I have to spend some more time on this, I guess, and figure out what's causing the problem.

I do notice that our tests are executed in parallel so maybe there's some race condition happening...

**Comment by gslowikowski** [comment]
I've just tested it on deadly simple project and it just works.

Scoverage is thread safe. You can see multiple `scoverage.measurements.*` files in `coverage-data` directory created by different testing threads. There should not be any race conditions. You can examine these files, if they contain all statement numbers (compare with `scoverage.coverage.xml` file).

I can add that you should call `coverageAggregate` in separate call. Everything before this task can be called in one call (`sbt coverage test fun:test coverageReport`).

I'm afraid, I cannot help you without seeing your build.

**Comment by jqno** [comment]
Apologies for the slow response.

I have prepared a new project which reproduces the issue. It's in the same repo: https://github.com/jqno/scoverage-issue

This time, instead of starting from a clean project and trying to build my way into the issue, I started from our existing project and stripping out as much as possible while still keeping the issue. There's probably still some stuff in there that isn't strictly necessary to reproduce the problem; if it's too much please let me know and I'll try to reduce further.

The file Coverage.scala contains two methods. One of them is called from a regular `test`, and the other from a `fun:test`.

You can reproduce as follows:

    sbt clean coverage test fun:test && sbt coverageReport

This generates a report where only the `fun:test` bit from Coverage.scala is covered, even though you can see in the sbt log that the method was called.

    sbt clean coverage fun:test test && sbt coverageReport

Now the report "flips around": only the `test` bit from Coverage.scala is covered.

It seems as if only the task which is executed last, is taken into acocunt in the coverage report. (If you run `test` without `fun:test`, or `fun:test` without `test`, then it works as expected.)

**Comment by gslowikowski** [comment]
There are no sources in your test project.

**Comment by jqno** [comment]
Apologies, you're right.

I hadn't noticed there was an entry `coverage` in our gitignore, and of course that's what I named my test classes... 😅 

Fixed now!

**Comment by gslowikowski** [comment]
Got it.

Main classes compilation cleans `scoverage-data` directory (see it in the [source code](https://github.com/scoverage/scalac-scoverage-plugin/blob/v1.3.0/scalac-scoverage-plugin/src/main/scala/scoverage/plugin.scala#L115-L119)). This removes already stored `scoverage.measurements.xxx` files containing coverage data.

The problem is source reformatting which constantly triggers recompilation.
Configure `scalariform` plugin (if possible) to skip reformatting when a file didn't change or disable it somehow during coverage generation (and remove the line turning off coverage from `StaticAnalysis.scala` file) and it will work as expected.

Additionally, I advise to upgrade Scoverage plugin version to latest `1.5.0`.

**Comment by jqno** [comment]
You're completely right. Thank you so much for finding this, and also explaining why it happens.

I'll see if I can configure scalariform in a different way. And I will take your advice and upgrade to 1.5.0 as well.

**Comment by jimschubert** [comment]
@gslowikowski thanks for that. We were also using scalariform and scoverage, and Scalariform's recompile was the culprit. Rather than reconfigure Scalariform, I've replaced it with shared project code settings and scalastyle.

**Comment by mirkof** [comment]
@jqno can you please update your Github example with the solution example?

**Comment by jqno** [comment]
@mirkof I was unable to (quickly) reconfigure Scalariform such that it kept working with our submodules. So instead, we decided to replace it with [Scalafmt](http://scalafmt.org/). This tool has to be called manually by default, by calling `sbt scalafmt`. To make sure the formatting policy is enforced, our CI server calls `sbt "scalafmt --test"`, which checks if all files are formatted properly. This has been working very well for us; it even caused some speed gains because our Play app doesn't recompile everything each time we change an html file.
