### ISSUE TITLE
1.5.0 running of tests with coverage enabled meses future tests by throwing scoverage.Invoker$ class not found

### ISSUE THREAD

**Issue by codingvlad** [scoverage/sbt-scoverage#217]
Hello,

I have an issue with the latest (1.5.0) version of the plugin. I have a suite of tests that do not fail after a fresh clean start. After I run once the command `sbt clean coverage test coverageReport`, the previous test suite fail with an error saying the class `scover.Invoker$` was not found. Is this some known issue?

Thank you.

**Comment by ckipp01** [comment]
This should now be fixed. Please do report back if you have any issues.

**Comment by SethTisue** [comment]
ah, I love the smell of ancient tickets closing
