### ISSUE TITLE
Codegrid and Statement list views are inconsistent

### ISSUE THREAD

**Issue by morgen-peschke** [scoverage/sbt-scoverage#223]
I'm having an issue interpreting some output in which the Codegrid and Statement list views appear to disagree about the level of coverage.

The Codegrid seems to indicate there is coverage over this path:
![image](https://user-images.githubusercontent.com/6216438/27051504-3b78e77a-4f6b-11e7-9d73-a7dd10212909.png)

The Statement list view indicates coverage is missing, twice, but I haven't been able to figure out what it's trying to tell me.
![image](https://user-images.githubusercontent.com/6216438/27051593-7ca54892-4f6b-11e7-82f7-8043a451a480.png)

Is this a bug, or am I missing something in how I'm supposed to interpret this?

**Comment by gslowikowski** [comment]
Maybe the uncovered `()` statements are from not implemented `else` clause. I can look into this deeper if you will create a simple test project.

**Comment by morgen-peschke** [comment]
I was able to confirm that this is the case using a simple test project. It looks like everything is working correctly, there's just a documentation gap.

[scoverage-issue-223.zip](https://github.com/scoverage/sbt-scoverage/files/1081611/scoverage-issue-223.zip)
