### ISSUE TITLE
Integration tests written in Python

### ISSUE THREAD

**Issue by krishhnaiyer** [scoverage/sbt-scoverage#224]
Hi All,

I am trying to measure code coverage for my Scala application. What are the steps to be followed to get code coverage using scoverage when integration tests are written in Python?

**Comment by gslowikowski** [comment]
Hi

Main classes must be written in Scala to be instrumented by Scoverage during compilation. Test classes can be written in any language, or you can run your instrumented application and test it manually.

I wonder, how does your build look like, but generally you need to:
- run `sbt coverage test` (or `sbt coverage compile` if you have no Java/Scala tests, only Python ones)
- run your Python tests the way you do it
- run `sbt coverageReport`

**Comment by krishhnaiyer** [comment]
I am trying to run my tests on docker but the server starts and stops immediately with the following log in Jenkins console,

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9002

(Server started, use Ctrl+D to stop and go back to the console...)

[info] p.c.s.NettyServer - Stopping server...

The following command is issued to start the server with scoverage enabled: 
activator -Dsbt.override.build.repos=true -Dsbt.repository.config=./repositories -Dsbt.log.noformat=true clean coverage "run 9002" &

**Comment by gslowikowski** [comment]
Does it work locally? Does it work remotely without `coverage`?

**Comment by krishhnaiyer** [comment]
Yes it runs locally and on docker also "sbt coverage test" runs fine and stops the server before executing the next command from docker image. 
I guess the issue here is to keep the server up and running while the next commands gets executed from docker script

**Comment by krishhnaiyer** [comment]
It runs fine locally and remotely  "sbt coverage test" runs the tests.

I guess the problem here is sbt coverage "run 9002" is stopping the server before executing the next commands from the script

**Comment by krishhnaiyer** [comment]
I am able to resolve this issue by compiling the application first and then deploying the application
1. activator -Dsbt.override.build.repos=true -Dsbt.repository.config=./repositories -Dsbt.log.noformat=true clean coverage dist
2. bin/test-project -Dhttp.port=9002 &

**Comment by ckipp01** [comment]
Seeing that this is very old, I'm going to close this as stale. If you still have questions on this scenario, please do report back and we can open this back up.
