### ISSUE TITLE
No way to skip some tests for coverage report or specify the test package to run and generate coverage report for.

### ISSUE THREAD

**Issue by KumarWaghmode** [scoverage/sbt-scoverage#225]
I have multiple tests inside my project but I want to generate the coverage report for only one package of tests. There is no way to specify the name of test to generate report for or skip unwanted tests for reporting.

**Comment by gslowikowski** [comment]
Do you want to skip some tests in the reports or executing at all when coverage is turned on?

**Comment by shashidesai** [comment]
I use tagging for the tests to separate out and that helps generating reports specifically for the tests tagged with a specific tag. 
something like this 
I have unit tests tagged with `UnitTestTag` and I run this command
`$ sbt clean coverage "test-only -- -n UnitTestTag" coverageReport`
does this help ?
