### ISSUE TITLE
scoverage-report not exists

### ISSUE THREAD

**Issue by gkarthik21** [scoverage/sbt-scoverage#227]
I am getting this error while trying to generate report.  Can you help to identify what was missing.

11:48:15 Build was aborted
11:48:15 Publishing Scoverage XML and HTML report ...
11:48:15 ERROR: Step ?Publish Scoverage Report? aborted due to exception: 
11:48:15 java.io.IOException: /localhome/project/target/scala-2.11/scoverage-report not exists
11:48:15 	at org.jenkinsci.plugins.scoverage.ScoveragePublisher.copyReport(ScoveragePublisher.java:114)
11:48:15 	at org.jenkinsci.plugins.scoverage.ScoveragePublisher.perform(ScoveragePublisher.java:66)
11:48:15 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
11:48:15 	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
11:48:15 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
11:48:15 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
11:48:15 	at hudson.model.Build$BuildExecution.post2(Build.java:185)
11:48:15 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
11:48:15 	at hudson.model.Run.execute(Run.java:1763)
11:48:15 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
11:48:15 	at hudson.model.ResourceController.execute(ResourceController.java:98)
11:48:15 	at hudson.model.Executor.run(Executor.java:410)

**Comment by buaya91** [comment]
Any chance you found a workaround for this?

**Comment by gkarthik21** [comment]
@buaya91 bump the sbt version

**Comment by mavais** [comment]
Did you guys find the issue. I'm building a multi module project with clean install using Scoverage Version 1.4.0-M5. 
My individual reports are generated but Jenkins build fails publishing coverage report because it is not able to find the aggregate report.
It generates the coverage for last module and then fails it
![2019-09-26_12-40-05](https://user-images.githubusercontent.com/30053207/65666269-eaa6f700-e05a-11e9-89dc-a11ba871bd0e.png)

**Comment by ckipp01** [comment]
I believe this should be fixed, but if the issue still persists, please do report back.
