### ISSUE TITLE
How to ignore files not tracked by some DVCS like git?

### ISSUE THREAD

**Issue by deeplook** [scoverage/sbt-scoverage#230]
Is there a way to tell scoverage to consider only files tracked by some DVCS like git? Note that this is not the same as to ignore those files described in some file like `.gitignore`.

**Comment by gslowikowski** [comment]
No.

You have only two settings for exclusions:
- [coverageExcludedPackages](https://github.com/scoverage/sbt-scoverage#exclude-classes-and-packages)
- [coverageExcludedFiles](https://github.com/scoverage/sbt-scoverage/blob/master/src/main/scala/scoverage/ScoverageKeys.scala#L10) (not described in README file)

**Comment by deeplook** [comment]
Well then it might be worth considering a config entry for an explicit list of files, which one could populate according to one's own needs, in this case like the following for `git`, based on this [StackOverflow snippet](https://stackoverflow.com/questions/3801321/git-list-only-untracked-files-also-custom-commands):

```scala
import sys.process.Process
val cmd: Seq[String] = "git ls-files --others --exclude-standard".split(" ")
val untrackedPaths: Array[String] = (Process(cmd).!!).trim.split("\n")
```

**Comment by ckipp01** [comment]
I think for the time being the `coverageExcludedFiles` and `coverageExcludedPackages` should suffice for this. If you still feel strongly about this, comment back, but it's not something I plan on implementing.
