### ISSUE TITLE
Publish for sbt 1.0.0

### ISSUE THREAD

**Issue by mielientiev** [scoverage/sbt-scoverage#233]

**Comment by imarios** [comment]
please!

**Comment by mielientiev** [comment]
@imarios I'm not sure, but the PR with sbt 1.0.0 support has been already merged https://github.com/scoverage/sbt-scoverage/pull/229 
So I suspect, that it should be enough to just release it

cc @dwijnand @eed3si9n

**Comment by mielientiev** [comment]
@gslowikowski any chance that it would be released in the short time?

**Comment by gslowikowski** [comment]
`1.5.1-SNAPSHOT` snapshot published to [Sonatype snapshots repository](https://oss.sonatype.org/content/repositories/snapshots/).

Test it please.

**Comment by mosesn** [comment]
@gslowikowski I tried it for sbt 1.0.0 and it seems to work. 🚢 🇮🇹

**Comment by liff** [comment]
@gslowikowski Works fine for me.

**Comment by mosesn** [comment]
@gslowikowski hey, have you had a chance to publish the stable 1.5.1 yet?

**Comment by fthomas** [comment]
1.5.1-SNAPSHOT works for me too.

**Comment by Lasering** [comment]
1.5.1-SNAPSHOT also works for me.

**Comment by nrinaudo** [comment]
I have tested 1.5.1-SNAPSHOT, seems to work for me.

**Comment by asflierl** [comment]
no (additional) issues with 1.5.1-SNAPSHOT so far

**Comment by nesc58** [comment]
For me 1.5.1-SNAPSHOT works like a charm.

**Comment by gslowikowski** [comment]
Version `1.5.1` released.
