### ISSUE TITLE
Please publish 1.5.1 to Maven Central

### ISSUE THREAD

**Issue by winitzki** [scoverage/sbt-scoverage#241]
Can't seem to find 1.5.1 in Maven Central. Please provide an official published artifact if possible. Thank you!

**Comment by gslowikowski** [comment]
It's there:
http://repo1.maven.org/maven2/org/scoverage/sbt-scoverage_2.10_0.13/1.5.1/ - version for SBT 0.13.x
http://repo1.maven.org/maven2/org/scoverage/sbt-scoverage_2.12_1.0/1.5.1/ - version for SBT 1.0.x

**Comment by winitzki** [comment]
Thank you!
