### ISSUE TITLE
Make dataDir configurable

### ISSUE THREAD

**Issue by btomala** [scoverage/sbt-scoverage#261]
I'm trying to run my integration tests in docker the problem is that the `dataDir` is set up as `crossTarget.value` which is taken from my local machine. Will be a lot of easier if this will be default but I can override this value.

**Comment by gslowikowski** [comment]
How/where will you create reports after the tests? Still in docker?

**Comment by btomala** [comment]
* I'm using DockerPlugin to build an image with instrumented code.
* The `dataDir` is set to the directory, e.g. `/tmp/my-app/coverage` needs to be the same on the building machine and inside a docker image.
* The coverage plugin generates there required files in `dataDir`, I add them to the `Universal / mappings` and docker plugin copy them into the docker image during the building process. 
* I deploy docker and run the integration tests.
* I'm copying `docker:/tmp/my-app/coverage` to `ci:/tmp/my-app/coverage` and run `sbt coverageReport` on ci machine.

A workaround for this PR is to create a directory with the same path what `crossTarget` has during the compilation, inside the docker and give access to it for the user which starting application. But this is one of the configuration option exposed by scoverage-plugin and should be exposed to users.

**Comment by zabbal** [comment]
If I understand what dataDir is (the place where results of "sbt coverage test" are stored which will be needed for "sbt coverageReport") than I'm interested in this issue as well. It's very convenient to split generation of coverage data from generation of report based on that data. Having ability to explicitly configure intermediate storage for the data which have to be shared between those stage would greatly simplify things.

**Comment by ckipp01** [comment]
This is now configurable in the more recent versions of sbt-scoverage.
