### ISSUE TITLE
Is there a way to run scoverage without instrumenting production code?

### ISSUE THREAD

**Issue by btomala** [scoverage/sbt-scoverage#264]
As it is mention in https://github.com/scoverage/sbt-scoverage/issues/128#issuecomment-304751944 when you will set the `coverageEnabled := true` in your `build.sbt` There is no way to build production code without instrumenting it. When I'm trying build tests with `coverageOn` flag, I got an exception about missing dependencies described in https://github.com/scoverage/sbt-scoverage/issues/263

So my question is how to run scoverage without instrumenting production code?

**Comment by gslowikowski** [comment]
Hi @btomala 

You shouldn't use `coverageEnabled := true` setting. Setting this value to false is for excluding in some modules of multi module build is for excluding then from coverage. Setting to true does not make sense.

**Comment by btomala** [comment]
I got it there were several issues related to my build. Thanks for the help :+1:
