### ISSUE TITLE
CoverageEnabled True

### ISSUE THREAD

**Issue by deepakmehra10** [scoverage/sbt-scoverage#274]
I just wanted to understand what would this coverageEnabled:= true would do.
I have configured this setting in build.sbt not sure what it would do, it the readme it says enable coverage directly in the build. Could you explain this a bit more true/false would not make any difference.

**Comment by gslowikowski** [comment]
Hi @deepakmehra10 

I would say that you should never set `coverageEnabled := true` in your build. It does not make sense.

You should turn coverage mode on with `coverage` task and turn it off with `coverageOff`. Behing the scenes these two tasks toggle the value of  `coverageEnabled in ThisBuild`.

Setting `coverageEnabled := false` on the other hand makes sense if you want to exclude some modules from coverage checking/reporting in multi module project. Modules with this setting will be excluded.

I think that the section about this setting in README file is misleading.

**Comment by deepakmehra10** [comment]
I completely agree with this, the section seems to be misleading. Thanks for your time, sir. Appreciate that
