### ISSUE TITLE
Modules were resolved with conflicting cross-version suffixes scoverage

### ISSUE THREAD

**Issue by Christewart** [scoverage/sbt-scoverage#275]
https://travis-ci.org/bitcoin-s/bitcoin-s-core/jobs/477518390#L1220

It appears that there is some issue with scoverage and `crossScalaVersions`? Here is the branch i am working off of. Note: this only fails on CI, not locally

https://github.com/Christewart/bitcoin-s-core/tree/0.0.3

**Comment by gslowikowski** [comment]
Hi @Christewart 

Look at these lines in Travis log:
```
[info] Setting Scala version to 2.11.12 on 8 projects.
[info] Excluded 2 projects, run ++ 2.11.12 -v for more details.
```

When you execute `sbt ++2.11.12 -v` you will see more informations:
```
[info] Setting Scala version to 2.11.12 on 8 projects.
[info] Switching Scala version on:
[info]     zmq (2.11.12, 2.12.7)
[info]     eclairRpc (2.11.12, 2.12.7)
[info]     doc (2.11.12, 2.12.7)
[info]     core (2.11.12, 2.12.7)
[info]     coreTest (2.11.12, 2.12.7)
[info]     rpc (2.11.12, 2.12.7)
[info]     bench (2.11.12, 2.12.7)
[info]     testkit (2.11.12, 2.12.7)
[info] Excluding projects:
[info]   * root ()
[info]     secp256k1jni (2.12.7)
```

The problem is with `secp256k1jni` module. It does not accept Scala `2.11.12`. When you remove:
```
//sbt documents recommend setting scalaversion to a fixed value
//to avoid double publishing
//https://www.scala-sbt.org/1.x/docs/Cross-Build.html
crossScalaVersions := {
  List("2.12.7")
}
```
from its `build.sbt` file, the build will work.

I wonder, why you need all this magic with Scala versions. I wouldn't mix pure Java module (`secp256k1jni`) which is Scala agnostic with all the other Scala modules in one build.

Additionally, why do you set `crossScalaVersions := Nil` for root module?

**Comment by gslowikowski** [comment]
Alternatively you can add:
```
coverageEnabled := false
```
to `secp256k1jni` module.

It doesn't contain any Scala code, so Scoverage will show nothing anyway.

**Comment by Christewart** [comment]
>Additionally, why do you set crossScalaVersions := Nil for root module?

This is suggested in the sbt documentation: 

https://www.scala-sbt.org/1.x/docs/Cross-Build.html#Cross+building+a+project

**Comment by Christewart** [comment]
This resolved my issue. Thank you!

**Comment by gslowikowski** [comment]
Side note

From https://www.scala-sbt.org/1.x/docs/Cross-Build.html#Cross+building+a+project:
>Note: crossScalaVersions must be set to Nil on the root project to avoid double publishing. 

and there is:
```
publish / skip := true
```
in the example.

If you skip publishing at all, you will not double publish for sure :)

I'm personally setting this `skip` flag in my projects, that's all.
