### ISSUE TITLE
Coverage for other test directories as well as standard

### ISSUE THREAD

**Issue by helena** [scoverage/sbt-scoverage#278]
I hunted around the code, google group and GitHub issues to see if there is something about this and thus far have not found an answer, apologies if this exists somewhere already.

In Akka, we run regular test and integration tests in their standard directories, but additionally have `multi-jvm` tests for which we need to report covererage as well, e.g.
* `root/submodule/src/multi-jvm/scala` // test sources also run during `sbt test` task
* `root/submodule/src/test/scala`

Is there a way to direct Scoverage to cover our root/submodule/src/multi-jvm dirs per module as well as test?

**Comment by patriknw** [comment]
but it seems to work just fine with multi-jvm tests. Not sure how it collects results from all jvms, but there are some results from `clean coverage multi-jvm:test coverageReport`

**Comment by gslowikowski** [comment]
@helena can you create simple test project showing your problem?

**Comment by helena** [comment]
@gslowikowski Closing, looks like we're good for now doing just local per-module usage. I was originally setting things up for a nightly Jenkins coverage job, also using the Jenkins coverage plugin. Works fine to `coverageReport` and `coverageAggregate` a few modules but consistently failed when running more than 3. Thanks.
