### ISSUE TITLE
No source root found

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [scoverage/sbt-scoverage#279]
I have the following project structure:

```
--- project/
 |
 +- servision/
 |
 +- anotherSubproject/
 |
 + build.sbt
```

Why does it complain about a source file belonging to my SBT build in the `project` directory?
Is this a bug?

```
java.lang.RuntimeException: No source root found for '/home/jenkins/workspace/Servision-rapido/project/ima_dbs.scala' (source roots: '/home/jenkins/workspace/Servision-rapido/servision/src/main/scala/', '/home/jenkins/workspace/Servision-rapido/servision/src/main/java/
```
There is no complain for other sourcers in `project`.
It exists `ima_dbs.scala` both in `servision/src/main/scala/somePackage` and in `project`, but they contents are different.

Using:
- sbt-scoverage 1.5.1, 
- Scala 2.12, 
- Java 8, 
- SBT 1.1.4
- Linux

**Comment by gslowikowski** [comment]
Hi @DavidPerezIngeniero 

Can you provide simple test project?

**Comment by DavidPerezIngeniero** [comment]
Is as simple as having a source file present both in `subproject/src/main/scala/mypackage/myfile.scala` and `project/myfile.scala`
What's important is the filename, instead of its contents.
In my case, both source files are different.

**Comment by DavidPerezIngeniero** [comment]
I've discovered something relevant to this problem:

`subproject/src/main/scala/mypackage/myfile.scala` is a symbolic link to `project/myfile.scala`
