### ISSUE TITLE
Issues with sbt-scoverage import

### ISSUE THREAD

**Issue by smarannarams** [scoverage/sbt-scoverage#280]
Hi Team,
I am new to scala as of now, I want to update my sbt-coverage to 1.5.1. from 1.0.4

When I did so, I am getting error as shown below

**error: value ScoverageKeys is not a member of object scoverage.ScoverageSbtPlugin
    ScoverageSbtPlugin.ScoverageKeys.coverageMinimum := 60,**

These are my plugins in plugins.sbt
addSbtPlugin("io.spray" % "sbt-revolver" % "0.7.2")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.13.0")
addSbtPlugin("io.gatling" % "gatling-sbt" % "2.1.0")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "0.8.5")

addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "0.6.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1")

My Sbt version in build.properties is sbt.version=0.13.12.

Can you please let me know what is the issue?

Also when I navigate from Intelij to the scoverage class its still pointing to sbt-coverage-1.0.4.jar. instead of 1.5.1

somehow I feel the desired jar 1.5.1 is not getting downloaded to dependencies.

Any help is much appreciated

**Comment by gslowikowski** [comment]
Hi @smarannarams 

Check https://github.com/scoverage/sbt-scoverage#notes-on-upgrading-to-version-130, or you can compare current readme with the one from `1.0.4` tag to see the differences in parameter declarations.

**Comment by gslowikowski** [comment]
Did it help? If yes, close this issue, pluese.

**Comment by ckipp01** [comment]
Seeing that there was no response I'm going to go ahead and close. If you're still having issues with the newest version, please do report back.
