### ISSUE TITLE
 Cause: java.lang.RuntimeException: java.net.BindException: Address already in use (Bind failed)

### ISSUE THREAD

**Issue by smarannarams** [scoverage/sbt-scoverage#281]
Hi Team,
 After updating to 1.5.1

addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1")
 When I run the tests its throwing below error

[info]   Cause: java.lang.RuntimeException: java.net.BindException: Address already in use (Bind failed)

I am not sure if it running all the test parallel instead of one after another.

Please let me know how to fix this issue.

my plugins:
plugins.sbt
------------
addSbtPlugin("io.spray" % "sbt-revolver" % "0.7.2")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.13.0")
addSbtPlugin("io.gatling" % "gatling-sbt" % "2.1.0")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "0.8.5")

addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "0.6.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1")

Java 1.8

build.properties
------------------
sbt.version = 0.13.17

build.sbt
----------
coverageMinimum := 60,
coverageFailOnMinimum := true,

**Comment by smarannarams** [comment]
I found solution

you need to add 
parallelExecution in Test := false in you build.sbt for tests execution else all tests run parallel and fight for port

**Comment by smarannarams** [comment]
I found solution

you need to add
parallelExecution in Test := false in you build.sbt for tests execution else all tests run parallel and fight for port

**Comment by gslowikowski** [comment]
Scoverage supports parallel test execution and it does not open any ports.

There problem must be somewhere else. The full stacktrace of the exception would be helpful.
