### ISSUE TITLE
Excluding lines/expressions from coverage calculation

### ISSUE THREAD

**Issue by jatcwang** [scoverage/sbt-scoverage#292]
Hi, first I want to say thanks for this project! It's a good tool.

When writing algorithms, there can be statement/expressions which should be impossibles given the algorithm, but can be reached given a bug in implementation. We still want to, say, throw an assertion error to provide good error messages to help track and fix the bug

I'd like to enforce 100% coverage but these impossible branches gets in the way.

Is there a way where we can instruct scoverage to skip certain lines?

**Comment by gslowikowski** [comment]
Hi @jatcwang.

Check
```

**Comment by jatcwang** [comment]
I'm so sorry! I glanced at the subsection title and thought it wasn't possible 😅 Thank you!
