### ISSUE TITLE
not found in repo1.maven.org

### ISSUE THREAD

**Issue by imrafaelmerino** [scoverage/sbt-scoverage#298]
I can't get it working. I get the following error:

not found: https://repo1.maven.org/maven2/org/scoverage/sbt-scoverage_2.13_1.0/1.6.2/sbt-scoverage-1.6.2.pom

scalaVersion := "2.13.1"

addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.6.2")

**Comment by gslowikowski** [comment]
Latest version is `1.6.0`.

**Comment by imrafaelmerino** [comment]
Thanks for the quick answer. I get the same result:

not found: https://repo1.maven.org/maven2/org/scoverage/sbt-scoverage_2.13_1.0/1.6.0/sbt-scoverage-1.6.0.pom

**Comment by imrafaelmerino** [comment]
I didn't add the plugin in the file project/scoverage.sbt (it's my first project with SBT :))
now it's working..
Thanks
