### ISSUE TITLE
Scoverage jar missing from Maven Central

### ISSUE THREAD

**Issue by yawaramin** [scoverage/sbt-scoverage#301]
Hello, getting a 404 on https://repo1.maven.org/maven2/org/scoverage/sbt-scoverage/1.6.1/sbt-scoverage-1.6.1.jar

But Maven Central says the package is available https://search.maven.org/artifact/org.scoverage/sbt-scoverage/1.6.1/jar

It looks like somehow the package publish did not succeed. Would it be possible to re-publish? Thanks.

**Comment by gslowikowski** [comment]
I don't know, what you are trying to do, but everything is in place:
- https://repo1.maven.org/maven2/org/scoverage/sbt-scoverage_2.12_1.0/1.6.1/
- https://repo1.maven.org/maven2/org/scoverage/sbt-scoverage_2.10_0.13/1.6.1/
Remember, this is SBT plugin and you have to declare it in your build as a plugin, not dependency. SBT will use proper URL. Yours is wrong.

**Comment by yawaramin** [comment]
Yeah I guess something really wonky is happening with my sbt resolution. Thanks for pointing that out!
