### ISSUE TITLE
Statement coverage different between local env and Travis

### ISSUE THREAD

**Issue by ww-gustavomuniz** [scoverage/sbt-scoverage#305]
I have a project in Scala that I'm working on.

In my local environment I run `sbt clean coverage test coverageReport` and I get: `Statement coverage.: 84.64%`.
I push all the changes to github, Travis runs, and after running all the tests I got a different result: `Statement coverage.: 82.72%`.

I'm using Scala 2.13.1 in the project, I have installed scala 2.12.8, java `openjdk version "1.8.0_202"`, sbt-coverage version 1.6.1.
I was using java `java version "1.8.0_191"`, I think this might be the problem, but no luck.

One weird thing is a colleague has the same version of Scala installed (2.12.8) however, he got the same test coverage than Travis, so it doesn't looks like an issue related to Scala version installed.

Any ideas?

**Comment by jcallin** [comment]
Not sure if you've solved this by now but this has happened to me when I had certain environment variables/java system props defined in the production env but not in my local env. You might have a condition which check for the existence of `ENV_VAR` or property `-Dmy.env.var=value` and only executes a code path if it exists. Your colleagues machine and your CI system might both have the variable, but it might be missing from your environment.

**Comment by gmarti** [comment]
We have the same problem on codefresh, it looks like it's because of something that didn't get clean by `sbt clean` but is cached by the CI between tests
Because if we start from clean checkout it seems to be consistent

**Comment by ckipp01** [comment]
Hello! What @gmarti mentions is most likely true. There shouldn't be a difference in the env.  I'll close this for now seeing that it's quite old, but if you have exhausted the options other mentioned here and are still hitting on the issue, please do report back!
