### ISSUE TITLE
Is sbt-scoverage going to support Dotty/Scala3?

### ISSUE THREAD

**Issue by gzoller** [scoverage/sbt-scoverage#316]

**Comment by ckipp01** [comment]
So this isn't really a question of sbt-scoverage supporting Scala 3, but more the actual compiler plugin. There is an issue for this here: https://github.com/scoverage/scalac-scoverage-plugin/issues/299

I'll close this for now to keep the conversation focused in there.

**Comment by DamianReeves** [comment]
I feel like this is relevant in that in the current state of things with no Scala3 support there is no good pattern for not running scoverage on Scala 3 builds when you cross compile. I find myself unable to use coverage when cross building, since `coverageEnabled` is not good enough.
