### ISSUE TITLE
NoSuchMethodError for scala 2.12.13

### ISSUE THREAD

**Issue by blast-hardcheese** [scoverage/sbt-scoverage#321]
For those impacted by this, #319 was incorrectly closed. See the end of that issue for an update as to where we are.

**Comment by kubukoz** [comment]
Blocked by https://github.com/scoverage/scalac-scoverage-plugin/issues/305

**Comment by ckipp01** [comment]
Thanks everyone for your patience. I was just able to get a v1.7.0 release made that should fix this and add support for both 2.12.13 and 2.13.5. Please try it out and report back with any issues.
