### ISSUE TITLE
sbt-scoverage

### ISSUE THREAD

**Issue by geraldstanje** [scoverage/sbt-scoverage#352]
hi,

how can i use sbt-scoverage with sbt 0.13.15? is there a way to still make it work?

**Comment by ckipp01** [comment]
I @geraldstanje we dropped support for sbt 0.13.15 with this last release. If you are still on 0.13.15 it's highly recommended update you sbt version. If you're unable to, you'll need to stay on an older version of sbt-scoverage.

**Comment by geraldstanje** [comment]
@ckipp01 the problem is im using bigtruedata/sbt:0.13.15-2.11.8 docker image for my builds. which is sbt 0.13.15 and scala 2.11.8 ... any alternative?

**Comment by ckipp01** [comment]
It looks like those docker images haven't been updated for the past 3 years https://hub.docker.com/r/bigtruedata/sbt, so again I'd recommend maybe looking into an alternative. I also see that the GitHub org doesn't exist either. I'm not fully sure what's all in this image, but if it's just a basic Scala image, it should be pretty easy to replace.

In order to use with 0.13.15 you'd need to go back to 1.6.x.

> also how to see the test coverage of each file in the project in percent?

You would need to look at the reports to get this info.

**Comment by geraldstanje** [comment]
@ckipp01 ok - any docker image you suggest to use for sbt with scale 2.11.8 with a newer sbt version? i need to update test coverage before stepping up to scala 2.12...

**Comment by ckipp01** [comment]
Without knowing your specific use-case, I have no idea what would be an appropriate image for you to use. It's entirely up to what you're actually doing in your project.

**Comment by geraldstanje** [comment]
using sbt-scoverage version 1.6.1 atm:

sbt clean coverage test coverageReport shows me:
[info] Generating scoverage reports...
[info] Written Cobertura report [/root/github.com/xxx/xxx/target/coverage-report/cobertura.xml]
[info] Written XML coverage report [/root/github.com/xxx/xxx/target/scoverage-report/scoverage.xml]
[info] Written HTML coverage report [/root/github.com/xxx/xxx/target/scoverage-report/index.html]
[info] Statement coverage.: 33.21%
[info] Branch coverage....: 3.68%
[info] Coverage reports completed
[info] All done. Coverage was [33.21%]

is there aything added in recent version which i really need to have?

**Comment by ckipp01** [comment]
> is there aything added in recent version which i really need to have?

Please read the release notes to determine this.

**Comment by ckipp01** [comment]
I'm going to go ahead and close this. Let me know if you have any other questions @geraldstanje
