### ISSUE TITLE
Publish for Scala 2.12.15?

### ISSUE THREAD

**Issue by SethTisue** [scoverage/sbt-scoverage#372]
when upgrading projects from sbt 1.5.5 to 1.6.0-M1 I'm seeing errors such as `Error downloading org.scoverage:scalac-scoverage-plugin_2.12.15:1.4.8`

this came up over at https://github.com/scala/community-build/pull/1486

**Comment by ckipp01** [comment]
So 1.4.8 is only published for 2.12.14. The 2.2.15 support was added in 1.4.9, which is the default version of scoverage in sbt-scoverage 1.9.0 (the latest release). I'm assuming that a project in the community build is just on an old version?
