### ISSUE TITLE
Is it possible to get the statement coverage value?

### ISSUE THREAD

**Issue by Chmieeel** [scoverage/sbt-scoverage#387]
is it possible to get the coverage of the statement or to automatically raise the minimum coverage?

**Comment by Chmieeel** [comment]
Well. I am currently using sbt-coverage and it is giving me report in teamcity job. Below is a description of what I wants to achieve:

If "statement coverage" is greater than "minimum coverage", the statement value replaces the minim (e.g. by taking the statement coverage value and replacing the minimum coverage value)

**Comment by ckipp01** [comment]
The automatic part of that is not possible.

**Comment by Chmieeel** [comment]
OK. Can I get statement coverage  value after checked coverage ? (I mean for example : put this value to variable)

**Comment by ckipp01** [comment]
You'd have to basically read the value from the report and then set it as outline here: https://github.com/scoverage/sbt-scoverage#minimum-coverage

**Comment by ckipp01** [comment]
I'm going to go ahead and close because I believe you have everything you need. If you still have questions feel free to comment back.
