### ISSUE TITLE
scoverage fails due to unresolved dependency path

### ISSUE THREAD

**Issue by prolific-dev** [scoverage/sbt-scoverage#392]
IDE_version: 

> - IntelliJ IDEA Ultimate 2021.2.3

Scala_version:

> - 3.1.0

build.properties: 

> - sbt.version=1.5.5

libraryDependencies:

>  - libraryDependencies += "org.scalactic" %% "scalactic" % "3.2.10"

>  - libraryDependencies += "org.scalatest" %% "scalatest" % "3.2.10" % "test"

plugins:

> - addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.9.2")

> - addSbtPlugin("org.scoverage" % "sbt-coveralls" % "1.3.1")

CI/CD:

> - Travis CI

> - Coveralls.io

When I use the following commands inside the sbt shell ```sbt clean test``` everything just works fine.
As soon as I activate ```coverage``` before ```test``` and try to run the tests trough sbt I get following output.

```
[IJ]coverage
[info] Defining ThisBuild / coverageEnabled
[info] The new value will be used by Compile / compile / scalacOptions, libraryDependencies
[info] Reapplying settings...
[info] set current project to my-project (in build file:/D:/Projects/my-project/)
[IJ]test
[warn]
[warn]  Note: Unresolved dependencies path:
[error] stack trace is suppressed; run 'last update' for the full output
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scoverage:scalac-scoverage-runtime_3:1.4.10
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\USER\.ivy2\localorg.scoverage\scalac-scoverage-runtime_3\1.4.10\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scoverage/scalac-scoverage-runtime_3/1.4.10/scalac-scoverage-runtime_3-1.4.10.pom
[error] Total time: 0 s, completed 04.11.2021, 16:23:17
```

I already tried downgrading all versions of the visible plugins and dependencies to avoid the problem. Nothing really changed.

For me it seems like as I activate coverage sbt tries to reference a library which is not reachable. In this case it would for what ever reason be the pom file of ```scalac-scoverage-runtime_3\1.4.10\``` that doesn't exist yet.

Has anyone an idea on that problem?

Thank you for helping me out!

PS.: Take it easy on me as this is my first issue I put out ever in my whole GitHub history.

**Comment by ckipp01** [comment]
Hello! Thanks for reporting.

scoverage isn't yet published for Scala 3. You can track the progress on it here: https://github.com/scoverage/scalac-scoverage-plugin/issues/299

**Comment by SethTisue** [comment]
welcome :-)
