### ISSUE TITLE
sbt-scoverage 2.0.0 fails on Windows with `[error] bad option: -P:scoverage:` errors

### ISSUE THREAD

**Issue by guizmaii** [scoverage/sbt-scoverage#440]
We have CIs running on Linux, macOS and Windows.

Since we updated to sbt-scoverage 2.0.0, we have the following error at compile time on Windows when we run the `sbt 'clean;coverage;test;coverageReport'` command:
```scala
[error] bad option: -P:scoverage:dataDir:D:\a\project-name\project-name\modules\common\target\scala-2.13/scoverage-data
[error] bad option: -P:scoverage:sourceRoot:D:\a\project-name\project-name
[error] bad option: -P:scoverage:excludedPackages:caliban.generator.*;com.project.name.api.client.generated.*;com.project.name.api.client.api.testkit.*
[error] bad option: -P:scoverage:reportTestName
[error] four errors found
[error] (common / Compile / compileIncremental) Compilation failed
[error] Total time: 50 s, completed Jun 27, 2022, 11:55:15 AM
```

The same sbt command on Linux and macOS works normally.

Could it be because of the `/scoverage-data` in `scoverage:dataDir:D:\a\project-name\project-name\modules\common\target\scala-2.13/scoverage-data` which should be `\scoverage-data` on Windows 🤔

**Comment by rolandtritsch** [comment]
Closed with #465
