### ISSUE TITLE
Does it support Scala 3.1.3?

### ISSUE THREAD

**Issue by imrafaelmerino** [scoverage/sbt-scoverage#451]
what I get:
No coverage data, skipping reports

**Comment by ckipp01** [comment]
Hey @imrafaelmerino, coverage for Scala 3 starts with 3.2.x. I'll add a note to the readme to make this clearer.

**Comment by imrafaelmerino** [comment]
thanks for the quick reply, really appreciate it

**Comment by imrafaelmerino** [comment]
doesn work with Scala 3.2.0-RC1

https://github.com/lampepfl/dotty/issues/15835
