### ISSUE TITLE
Compatibility with Scala 2.12

### ISSUE THREAD

**Issue by gmendonca** [scoverage/sbt-scoverage#461]
Hi 👋 It seems that from 2.0.1 onwards I started to get the same error previous described here: 
https://github.com/scala/scala/pull/9743

```
[error] 	* org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over {1.0.6}
[error] 	    +- org.scoverage:scalac-scoverage-reporter_2.12:2.0.1 (depends on 2.1.0)
[error] 	    +- org.scalatra.scalate:scalate-util_2.12:1.8.0       (depends on 1.0.6)
[error] 	    +- org.scala-lang:scala-compiler:2.12.16              (depends on 1.0.6)
[error] 	    +- com.typesafe.play:twirl-api_2.12:1.3.13            (depends on 1.0.6)
```

Wondering if we could keep the compatibility for 2.12?

**Comment by seanrohead** [comment]
If you update to Scala 2.12.17, it will remove one of the conflicts (scala-compiler), but then it's up to scalatra and play to update their libraries to use scala-xml 2.1.0 to get rid of the other two conflicts

**Comment by ckipp01** [comment]
You can see the bigger conversation about this in https://github.com/scala/bug/issues/12632 and also a fix for it. We're in an odd situation for the time being where half the ecosystem has switched and the other not. So the other plugins will need to bump.
