### ISSUE TITLE
sbt-scoverage plugin installation failing with dependencies

### ISSUE THREAD

**Issue by raviteja-oops** [scoverage/sbt-scoverage#466]
Hi, I'm trying to install sbt-scoverage. It's failing with the dependencies. I used below statement as part of project/plugin.sbt.

libraryDependencies += "org.scoverage" % "sbt-scoverage_2.12_1.0" % "2.0.4"

Please find the attached screen shot for the dependency plugin errors

![sbt-scoverage dependency error png](https://user-images.githubusercontent.com/57656896/194474826-dd03a0a2-f6ca-433d-b386-00aaaa6a1194.jpg)

**Comment by ckipp01** [comment]
> Hi, I'm trying to install sbt-scoverage. It's failing with the dependencies. I used below statement as part of project/plugin.sbt.

libraryDependencies += "org.scoverage" % "sbt-scoverage_2.12_1.0" % "2.0.4"

Firstly, it's recommend to use the following unless it causes issues:

```
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "x.x.x")
```

Looking at your error I see you're using 2.11. Scoverage no longer support Scala 2.11. The last version of scoverage that did was 1.4.11.

It's recommended to try and bump the version of Scala you're using to a more modern version.
