### ISSUE TITLE
Please release for Scala 2.13.10

### ISSUE THREAD

**Issue by saeltz** [scoverage/sbt-scoverage#468]
I see that scalac-scoverage-pluign v2.0.7 was released with support for Scala 2.13.10. Could you please release sbt-scoverage for Scala 2.13.10 as well?

See https://github.com/scapegoat-scala/scapegoat/issues/682.

**Comment by ckipp01** [comment]
Hey @saeltz 2.0.5 has already been release for the sbt-scoverage plugin. This version brings in the 2.0.7 version of scoverage.

**Comment by saeltz** [comment]
Thanks, Chris!
