### ISSUE TITLE
Binary incompatibility after 1.9.3 when used together with sbt-scalastyle-plugin

### ISSUE THREAD

**Issue by avinash-anand** [scoverage/sbt-scoverage#477]
Not sure where to report this. but, we have a project where we have both scalastyle plugin and scoverage plugin and when trying to upgrade scoverage plugin, it fails with below error:

[info] loading project definition from C:\Avinash\workspace\tools\sbt-scoverage-demo\project
[error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over 1.0.6
[error] 	    +- org.scoverage:scalac-scoverage-reporter_2.12:2.0.7 (depends on 2.1.0)
[error] 	    +- org.scalariform:scalariform_2.12:0.2.0             (depends on 1.0.6)
[error]
[error]
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel

Current working versions:
```
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.9.3")
addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "1.0.0")
```

fails with above error when upgrading  scoverage to any higher version.

repo with minimal code to reproduce - https://github.com/avinash-anand/sbt-scoverage-demo

**Comment by ckipp01** [comment]
Please see #471,  #469, #466, or #461 and please do search for past issues in the future.
