### ISSUE TITLE
[Question] How to use plugin in an enterprise environment?

### ISSUE THREAD

**Issue by bilal-fazlani** [scoverage/sbt-scoverage#484]
We are behind an enterprise artifactory instance and unable to download this pluging using `addPlugin` function.

when using 

```
libraryDependencies += "org.scoverage" % "sbt-scoverage_2.12_1.0" % "x.x.x"
```

how to enable the plugin in sbt?

**Comment by bilal-fazlani** [comment]
I think I am missing some knowledge about plugins are resolved by sbt.

The readme says

> <img width="847" alt="image" src="https://user-images.githubusercontent.com/3396271/202698054-b0def2ff-2a07-48b6-bcc7-86704d578344.png">

I am not 100% sure what an enterprise environment means here.. but I am guessing I am in that enterprise environment because for me sbt keeps saying it can't find the plugin.

but when I use `libraryDependencies += "org.scoverage" % "sbt-scoverage_2.12_1.0" % "x.x.x"` sbt does not complain.

And my questions is when I add it like that, sbt does not expose coverage related commands in sbt shell. How to do I execute `coverageReport` when I use `libraryDependencies` instead of `addSbtPlugin`

I hope this making some sense. I am not sure why sbt is not resolving this plugin. I can only blame the fact that we are not allowed to use maven as a resolver directly. But we have to via an enterprise artifactory.

**Comment by ckipp01** [comment]
Just added it in as a `libraryDependency` like you have should be all you need. For example I just tried with a fresh hello-world sbt project and included the following in my `project/plugins.sbt`

```
libraryDependencies += "org.scoverage" % "sbt-scoverage_2.12_1.0" % "2.0.6"
```
When starting up sbt and doing `plugins` I see the folowing:

```
sbt:sbt-hello-world> plugins
In build /Users/ckipp/Documents/scala-workspace/sbt-hello-world/:
  Enabled plugins in myproject:
    ... 
    scoverage.ScoverageSbtPlugin
```

This shows me that the `ScoverageSbtPlugin` is there and I do have all the `coverage` related commands I'd expect. Can you check the output of `plugins` and see if it shows scoverage in there?

**Comment by bilal-fazlani** [comment]
Working now :) not sure why it was failing earlier. Thank you for your help! 😄
