### ISSUE TITLE
Release 8ba258c

### ISSUE THREAD

**Issue by nrinaudo** [scoverage/sbt-scoverage#489]
Commit 8ba258cff5f44973b74c45ff4792719d8e551279 makes sbt-scoverage work under Windows. I work under Windows. I would quite like scoverage to work for me :)

Unless I'm mistaken, that commit is not part of the latest release. If that's correct, would it be possible to cut a new release that includes it?

**Comment by ckipp01** [comment]
Hey @nrinaudo that commit was in the v2.0.6 release. We're currently on v2.0.07 so you should be good. If not, please do report back.

**Comment by nrinaudo** [comment]
Huh. I just went by https://search.maven.org/artifact/org.scoverage/sbt-scoverage, which seemed to stop at 2.0.5. Will comfirm soon as I’m behind a keyboard, thanks!

**Comment by ckipp01** [comment]
Ah, that's super odd. I'm not sure what's going on there, but you can see on https://repo1.maven.org/maven2/org/scoverage/sbt-scoverage_2.12_1.0/ that there are more releases.

**Comment by nrinaudo** [comment]
That is really weird! But, yes, the “secret” version is available and fixes my issue. Thank you very much for your help.
