### ISSUE TITLE
Package / file exclusion does not work with Scala 3

### ISSUE THREAD

**Issue by kyri-petrou** [scoverage/sbt-scoverage#525]
Hi there. There seems that some coverage settings (primarily `coverageExcludedPackages` and `coverageExcludedFiles`, but I believe some other ones might be affected) are not working with Scala 3.

The easiest way to reproduce is by cloning the [sbt-scoverage-samples repo](https://github.com/scoverage/sbt-scoverage-samples), adding the following line to `build.sbt`:
```
coverageExcludedPackages := ".*"
```
and then running 
```
sbt coverage +test +coverageReport
```

This yields the following:

Scala 2:
```
[success] Total time: 13 s, completed 23 Dec 2023, 12:55:46 pm
[info] Statement coverage.: 100.00%
[info] Branch coverage....: 100.00%
[info] Coverage reports completed
```

Scala 3:
```
[info] Statement coverage.: 65.20%
[info] Branch coverage....: 33.33%
[info] Coverage reports completed
```

**Comment by ckipp01** [comment]
Hey @kyri-petrou, this is actually a limitation in the implementation of how coverage works with Scala 3. You can read more about it [here](https://github.com/lampepfl/dotty/discussions/17685). So it'd need to be added upstream in order for this to work.

**Comment by kyri-petrou** [comment]
@ckipp01 aghh I see. Thanks!

**Comment by ivanobulo** [comment]
I created an MR to address the issue. It would benefit from the upstream changes, but it is not required. Coverage data can be filtered after it was collected.

**Comment by mcanlas** [comment]
What is an "MR"?

**Comment by eschizoid** [comment]
hey @ivanobulo I just tried release `3.4.2-RC1` and I am still unable to exclude packages or files using any of these options:

```
coverageExcludedPackages := ...
coverageExcludedFile           := ...
```

Wondering if I could be missing something?

**Comment by alberto-spadoni3** [comment]
Could someone kindly explain me how can i exclude an entire package and all its subpackages from the scoverage report on Scala 3.4?
How can i exclude files and packages by passing the filter flags to the compiler options?

**Comment by eschizoid** [comment]
> Could someone kindly explain me how can i exclude an entire package and all its subpackages from the scoverage report on Scala 3.4? How can i exclude files and packages by passing the filter flags to the compiler options?

https://docs.scala-lang.org/overviews/compiler-options/index.html

and i just added this flag:

```
"-coverage-exclude-files:packages_to_be_excluded"
```

**Comment by TonioGela** [comment]
@ckipp01 is upstream now fixed? Can we proceed implementing the fix that passes the proper flag to the compiler?

**Comment by jozic** [comment]
Scala 3 supports file and class/package exclusions since 3.4.2
scoverage-maven-plugin was updated recently to support Scala 3 compiler flags

https://github.com/scoverage/scoverage-maven-plugin/pull/237

**Comment by ckipp01** [comment]
> @ckipp01 is upstream now fixed? Can we proceed implementing the fix that passes the proper flag to the compiler?

Yes, I believe this is fixed, but I also haven't been following. Please do submit a PR for it.

**Comment by TonioGela** [comment]
> Scala 3 supports file and class/package exclusions since 3.4.2 scoverage-maven-plugin was updated recently to support Scala 3 compiler flags
> 
> [scoverage/scoverage-maven-plugin#237](https://github.com/scoverage/scoverage-maven-plugin/pull/237)

Can you work on PR for sbt-scoverage too please :D ? I would do that but I assume you're more proficient with it given that you did it for maven :)

**Comment by jozic** [comment]
@TonioGela @ckipp01  #541
