### ISSUE TITLE
401 Content access is protected by token

### ISSUE THREAD

**Issue by rolandtritsch** [scoverage/sbt-scoverage#544]
@ckipp01 @jozic 

https://github`.com/scoverage/sbt-coveralls/issues/311

Hi Chris, et.al., 

See above ...

I can't publish (sbt-coveralls) to maven anymore.

Saw that you updated the credentials for sbt-scoverage a week ago.

Can you share the new credentials and/or update the credentials on sbt-coveralls?

Was also wondering, if now is a good time to migrate to `central.sonatype.org` (assuming we are still using the legacy repo)?

If so, we need somebody with access to the `org.scoverage` domain server (to do the registration on `central`). Any idea who that would be?

**Comment by jozic** [comment]
I suggest we set up secrets on the org level, they will be available for all repos then

**Comment by rolandtritsch** [comment]
Hi @jozic. Sounds good. Do you have the credentials? Can you set it up?

**Comment by jozic** [comment]
I have some credentials I've got from Chris which I use to release maven plugin, but I don't have access to org level settings to set it up
I think @ckipp01 can do that

**Comment by rolandtritsch** [comment]
Hi @jozic. If you share the credentials with me by email (roland@tritsch.org) or 1password, then I can set it up. I have access to the org settings.

**Comment by ckipp01** [comment]
@rolandtritsch I just updated the token details in the sbt-coveralls CI. You should be able to try again. Let me know if it doesn't work.

**Comment by rolandtritsch** [comment]
![image](https://github.com/user-attachments/assets/44a9d9a1-6628-4441-b611-fe7676edd767)

BOOM!!! We are back in business!!! Thanks!!! @ckipp01

**Comment by jozic** [comment]
@ckipp01 but what do you think of setting sonatype credentials on the org level?
Seems like that should be a better solution especially if all the repos use the same account

**Comment by jozic** [comment]
Hey folks, so, the job i set up to publish snapshots for scoverage-maven-plugin fails for some time now with 

```
status: 401 Content access is protected by token
```

https://github.com/scoverage/scoverage-maven-plugin/actions/runs/10550370598/job/29226451931
it used to work when i set it up initially

i believe this is the same issue which can be solved if proper credentials are set on the org level.
Could any of you please help me with it? Thank you

**Comment by rolandtritsch** [comment]
Only @ckipp01 has the power to fix this.

**Comment by jozic** [comment]
@ckipp01 could you please set it up on org level? or at least unlock me, otherwise i'm afraid i won't be able to release new versions of maven plugin
thank you!

**Comment by ckipp01** [comment]
Hey @jozic, I just set these at the org level now so this should be good to go. Make sure to delete them at the repo level as well so they don't conflict.
