### ISSUE TITLE
Fix(ed) maven-central badge

### ISSUE THREAD

**Issue by rolandtritsch** [scoverage/sbt-scoverage#545]
Hi @ckipp01,

I noticed that the `maven-central` badge in the README did not show the correct version number.

Looked into it.

The heroku app seems to have stopped working (shows the wrong/an old(er) version).

![heroku](https://maven-badges.herokuapp.com/maven-central/org.scoverage/sbt-scoverage/badge.svg)

Tried shield.io, but it cannot find the version.

![shields](https://img.shields.io/maven-central/v/org.scoverage/sbt-scoverage)

As a workaround I suggest to use the github-release version.

https://github.com/scoverage/sbt-scoverage/commit/2118fda70ebe9e6a36f2130639feb31ed4a9b150

Wanted to push that commit to my fork and do a PR, but pushed it by accident to `scoverage`. Sorry about that.

Doing this issue to document what happened.

Let me know, if you have a better idea. Happy to do a PR to revert the change.

**Comment by ckipp01** [comment]
You should also be able to use the badges from [scaladex](https://index.scala-lang.org/scoverage/sbt-scoverage/badges).

**Comment by rolandtritsch** [comment]
https://github.com/scoverage/sbt-scoverage/pull/546

Yep. That works. Here is the PR. Feel free to merge or let me know, if you want to merge.

**Comment by ckipp01** [comment]
Closed via #546
