### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jmodrako** [scoverage/sbt-scoverage#555]
Hey Team! Can you create a new release as the latest changes include fix for scala 3.5.0 package exclusions?

https://github.com/scoverage/sbt-scoverage/compare/v2.1.1...main

**Comment by ckipp01** [comment]
In the processing of getting the new scoverage published with the new 2.12.20 support, and once that's done I'll update the base version in the plugin and release this as well 👍🏼

**Comment by ckipp01** [comment]
https://github.com/scoverage/sbt-scoverage/releases/tag/v2.2.0 is now release!
