### ISSUE TITLE
Plugin for scala 2.13.14 is missing

### ISSUE THREAD

**Issue by goshacodes** [scoverage/sbt-scoverage#559]
Hello, plugin for scala 2.13.14 is missing. Could you please publish it?

**Comment by SethTisue** [comment]
https://github.com/scoverage/scalac-scoverage-plugin/pull/616 was closed months ago. Can you be more specific about what you believe the problem to be? What exactly did you try and exactly what error message or other unexpected behavior did you see?

Is it possible you're confused between sbt-scoverage (the sbt plugin) and https://github.com/scoverage/scalac-scoverage-plugin (the compiler plugin)?

**Comment by goshacodes** [comment]
Sorry for not detailed issue, I'll be more specific tomorrow

**Comment by goshacodes** [comment]
I use "org.scoverage" % "sbt-scoverage" % "2.0.8" in my project. Updated Scala to 2.13.14 and now it can't find the plugin. I guess I should update version to the latest)

**Comment by ckipp01** [comment]
We don't backpublish version @goshacodes. You either need to update your version of sbt-scoverage to bring in the latest version of scoverage, which will give you a version that is published for 2.13.14, or you'd need to set your `coverageScalacPluginVersion` sbt key to the latest version of scoverage that brings in support. Doing a bump in your sbt plugin version should by far be the easiest and the versions are quite stable, so it shouldn't cause any issues for you to bump.

**Comment by goshacodes** [comment]
Ok, thank you!
