### ISSUE TITLE
Coverage not excluding packages or files after upgrading to scala 3 and play 3

### ISSUE THREAD

**Issue by rohanr-kmon** [scoverage/sbt-scoverage#568]
Recently upgraded project to Scala 3.3.3 (was using scala 2 before), play 3.0.5 and sbt-scoverage 2.2.0. The below code to exclude route files was functional before but doesn't seem to be working anymore:

```
    coverageExcludedPackages := "<empty>;Reverse.*",
    coverageExcludedFiles := ".*Routes.*",
```

Coverage has dropped from 56% to 30% and i can't seem to exclude the router files with any regex combos. Are there any known bugs?

**Comment by ckipp01** [comment]
Hey @rohanr-kmon this was merged in, but just not released yet. I just cut a new release, 2.2.2, which should fix this for you. Feel free to update (might take like 30 min to propagate), but then report back if it works for you or not.

**Comment by jozic** [comment]
Just a reminder, Scala 3.3.4+ or 3.4.2+  is required 

https://github.com/scoverage/sbt-scoverage/pull/561

**Comment by rohanr-kmon** [comment]
Thank you @ckipp01 and @jozic !
