### ISSUE TITLE
HTML Report not generated when Tests are exluded via Filter

### ISSUE THREAD

**Issue by mavilein** [scoverage/sbt-scoverage#59]
Hey,

i originally opened the following bug, which i am still stuggling with: https://github.com/scoverage/sbt-scoverage/issues/52
This bug caused our Tests to fail, which were relying on Browser Interaction with Selenium. Therefore i wanted to simply exclude those tests for now until the bug might get fixed. As they should not run at all, i used the following:

```
instrumentSettings

testOptions in ScoverageTest := Seq(Tests.Filter(s => !s.endsWith("MediumSpec")))
```

The affected Tests end with the suffix MediumSpec. The tests are indeed not run when we call **scoverage:test**, but in the end the HTML Report does not get generated. I can see the folder scoverage-data in my target directory. But the report folder is missing. If i remove this line, everything works as expected.

**Comment by t3hnar** [comment]
I can still see this issue...
