### ISSUE TITLE
`coverageExcludedFiles` does not seem to have the expected behavior

### ISSUE THREAD

**Issue by massenz** [scoverage/sbt-scoverage#65]
Please feel free to close this if it's me missing the point, but when using `coverageExcludedFiles` I would expect _the files_ matching the RegEx not to be include in the **coverage** report.

However, they seem to still be included in the coverage calculation and overall main summary page, but then, when clicking on the link they give essentially a 404.

Again, not sure that I'm fully understanding what the "excluded files" behavior is supposed to be, but, as a user, I'd say that the current behavior is, at least, surprising.

This a screenshot of the summary page for the `controllers.ref` package:

![exfiles-1](https://cloud.githubusercontent.com/assets/1153951/5138582/065e7492-7106-11e4-88b7-755dc451b8cc.png)

if then one clicks on any of the `.scala` classes on the right (eg, the `ReverseApiController`): this is what comes out:

![ex-files-2](https://cloud.githubusercontent.com/assets/1153951/5138594/2e33c288-7106-11e4-869e-92a349bf86a3.png)

**Comment by sokrahta** [comment]
scoverage is picking up target/scala-2.10/sbt-0.13/src_managed/main/sbt-buildinfo/BuildInfo.scala

**Comment by JeffAtDeere** [comment]
:+1: It most definitely is picking up sources under target.

**Comment by sfosdal** [comment]
I can also confirm this

**Comment by c33-cooper** [comment]
@sksamuel - was there any resolve for 'not picking up sources under target' as mentioned above?

**Comment by 2beaucoup** [comment]
for me, files under src_managed are unfortunately picked up as well.

**Comment by gslowikowski** [comment]
I've just checked the case with `BuildInfo` and it works. 

`coverageExcludedFiles` is a a regexp, without `.scala` suffix

My setup:

`project/plugins.sbt`:
```scala
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.7.0")
```

`build.sbt`:
```scala
val root = (project in file("."))
  .enablePlugins(BuildInfoPlugin, ScoverageSbtPlugin)
  .settings(
    buildInfoKeys := Seq[BuildInfoKey](name, version, scalaVersion, sbtVersion),
    buildInfoPackage := "buildinfo",
    coverageExcludedFiles := ".*buildinfo.BuildInfo",
    // or: coverageExcludedPackages := "buildinfo\\.BuildInfo",

    // other settings here
  )
```
I always prefer `coverageExcludedPackages` over `coverageExcludedFiles` because you can have different file separators on different OS'es. That's why I used dot (which means any character in regexp) between `buildinfo` and `BuildInfo`. There will be `/` (slash) character on *nix and Mac systems and `\` (backslash) on Windows systems.

BTW, the name `coverageExcludedPackages` is misleading, is should be named `coverageExcludedClasses`.

Probably documentation should be made more clear about these parameters.

**Comment by sfosdal** [comment]
Is there some reason to not ignore the src files under target by default? Maybe I'm missing the value.

**Comment by gslowikowski** [comment]
They are ignored

**Comment by sfosdal** [comment]
ah, maybe it's something on my end then.  Thanks!

**Comment by gslowikowski** [comment]
What files you want to exclude and what is your `coverageExcludeFiles` property's value?

**Comment by 2beaucoup** [comment]
> They are ignored

Doesn't seem to be the case for `target/src_managed` or (`target/scala-2.12/src_managed` in my case).

**Comment by gslowikowski** [comment]
My generated `BuildInfo.scala` file (project configuration described [above](https://github.com/scoverage/sbt-scoverage/issues/65#issuecomment-339458133)) is located in `target/scala_2.12/src_managed/main/sbt_buildinfo` directory and exclusions work properly.

If anybody still has similar problems, add comment here with information:
- what file(s) you want to exclude,
- what is your `coverageExcludeFiles` property's value

and I will try to help.
