### ISSUE TITLE
Build for Scala 2.11.x?

### ISSUE THREAD

**Issue by enelson** [scoverage/sbt-scoverage#67]
Is there a plan to build this for Scala 2.11.x? I'm having issues using this plugin as it implies the project Scala version to lookup the remote artifact. My project uses 2.11.x, so SBT keeps sending me the following error. Is there an easy way to tell the plugin to just look for 2.10.x, while leaving the project level version alone?

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scoverage#sbt-scoverage;1.0.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          org.scoverage:sbt-scoverage:1.0.0 (scalaVersion=2.11, sbtVersion=0.13)
```

**Comment by sksamuel** [comment]
Closing this because sbt plugins don't have the cross build suffix. Eg
http://dl.bintray.com/sbt/sbt-plugin-releases/org.scoverage/sbt-scoverage/scala_2.10/sbt_0.13/
