### ISSUE TITLE
coverageAggregate creates incorrect links

### ISSUE THREAD

**Issue by massenz** [scoverage/sbt-scoverage#69]
[issue originally reported in [Issue #13 ]] 

I can confirm that the link to the sub-project's files are broken.
For example:

```
Link to a package summary page (resolves just fine):
file:///home/marco/workspaces/scala/sentinel/target/scala-2.11/scoverage-report/com.alertavert.sentinel.persistence.mongodb.html 

Link to the file (goes 404):
file:///home/marco/workspaces/scala/sentinel/sentinel_core/src/main/scala/com/alertavert/sentinel/persistence/mongodb/CreatorSerializer.scala.html
```

should be instead:

```
file:///home/marco/workspaces/scala/sentinel/sentinel_core/target/scala-2.11/scoverage-report/com/alertavert/sentinel/persistence/mongodb/CreatorSerializer.scala.html
```

is it possible that the path is taken from the XML (apart from the `.html` suffix, the path used resolves to the actual location of the `.scala` file)?

Cursorily browsing around, it would appear to me that the simplest fix would be to bring in everything from the sub-project's `scoverage-report` folder into the top-level project's folder, apart from the `index.html`, `overview.html` and `packages.html` - in the XML the refs to the source files are correct, and then adjust the links to the files.

**Comment by gslowikowski** [comment]
Try `1.0.5-SNAPSHOT` version please, add:
```scala
resolvers ++= Seq( Classpaths.sbtPluginSnapshots, Resolver.sonatypeRepo("snapshots") )

addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.0.5-SNAPSHOT")
```
to your `project/plugins.sbt` file.

**Comment by kurtkopchik** [comment]
Is there an ETA on when the official 1.0.5 version will be released? The aggregate reporting fix is working great in the snapshot release.

**Comment by RichardBradley** [comment]
This is fixed now, I think.

**Comment by ckipp01** [comment]
I believe this should be fixed now. If this is still an issue, please do report back.
