### ISSUE TITLE
Multi-project reports are not generated by "coverage" task. 

### ISSUE THREAD

**Issue by wvandrunen** [scoverage/sbt-scoverage#70]
When I run the coverage task on my multi-project setup, only the report for the root project is generated. When I run the coverageReport task all the reports are generated correctly.

Does this mean that something is broken or that the documentation is lacking this instruction?

**Comment by RichardBradley** [comment]
Is this fixed? Multi-project reports work for me.

**Comment by ckipp01** [comment]
Multi-projects seem to be working as expected. If you still do have any issues, please do report back.
