### ISSUE TITLE
Incorrect links containing .../scoverage-report/(empty)/... in scoverage 1.0.1

### ISSUE THREAD

**Issue by aginiewicz** [scoverage/sbt-scoverage#71]
For my project, scoverage generates incorrect links for subproject with only macros. This is already live in master branch on https://bitbucket.org/specdevs/specgine - we have convinance task "sbt verify" that cleans the projects, runs scalastyle on all, then generates reports and finally aggregates them. Running it should be enough to see the effect. Links work in "engine" project, while fail in "macros" project.

If it helps, I keep macros in package-level objects or package objects (depending on situation, but behaviour of scoverage is the same) with no classes - only methods. See https://bitbucket.org/specdevs/specgine/src/HEAD/macros/src/main/scala/states.scala?at=master for example. In this case, generated link is ./macros/target/scala-2.11/scoverage-report/(empty)/states.scala.html instead of /macros/target/scala-2.11/scoverage-report/states.scala.html.

**Comment by ckipp01** [comment]
Seeing that this is 7 years old now, I'm going to close. If you're still hitting on this with the current version, please do report back.
