### ISSUE TITLE
Unable to use plugin

### ISSUE THREAD

**Issue by rcsenkbeil** [scoverage/sbt-scoverage#81]
I'm using Scala 2.10.4 with sbt 0.13.5 and tried to add version 1.0.1 of sbt-scoverage to the project I work on.

Adding this plugin resulted in the compilation failing for [Spark Kernel](https://github.com/ibm-et/spark-kernel). I even tried adding the plugin and runtime dependencies directly to the project and I still get these failures. Any thoughts on why that might be? Am I doing something wrong?

```
[error] (root/compile:compile::scalacOptions) java.lang.Exception: Fatal: scalac-scoverage-plugin not in libraryDependencies
[error] (kernel/compile:compile::scalacOptions) java.lang.Exception: Fatal: scalac-scoverage-plugin not in libraryDependencies
[error] (kernel-api/compile:compile::scalacOptions) java.lang.Exception: Fatal: scalac-scoverage-plugin not in libraryDependencies
[error] (client/compile:compile::scalacOptions) java.lang.Exception: Fatal: scalac-scoverage-plugin not in libraryDependencies
[error] (protocol/compile:compile::scalacOptions) java.lang.Exception: Fatal: scalac-scoverage-plugin not in libraryDependencies
[error] (macros/compile:compile::scalacOptions) java.lang.Exception: Fatal: scalac-scoverage-plugin not in libraryDependencies
```

**Comment by sksamuel** [comment]
Can you try 1.0.2 just to rule out a couple of bugs that were fixed.

**Comment by sksamuel** [comment]
Your scoverage version is very old here:
https://github.com/ibm-et/spark-kernel/blob/master/project/plugins.sbt

Are you working on a branch?

**Comment by rcsenkbeil** [comment]
I am working in a branch. I just pushed the failing code here: https://github.com/ibm-et/spark-kernel/tree/FixTravisSupport

I'm also using sbt-coveralls, which I thought needed version 1.0.1 of sbt-scoverage.

**Comment by rcsenkbeil** [comment]
I just tried updating to 1.0.2 of sbt-scoverage and get the same failures.

**Comment by rcsenkbeil** [comment]
Updated above to new branch using 1.0.2. I removed the dependency references to scalac-scoverage-plugin/runtime since they do not seem to be detected.

**Comment by rcsenkbeil** [comment]
Figured it out. It was our own mistake as we were overwriting the library dependencies in Common.scala rather than appending to them. Sorry about that!

**Comment by sksamuel** [comment]
Ok great
