### ISSUE TITLE
java.io.FileNotFoundException in scalajs project

### ISSUE THREAD

**Issue by fommil** [scoverage/sbt-scoverage#82]
I'll link you to a failing hashcode of my project shortly, I'm running scoverage on the JVM part of my scalajs project and getting this when doing `sbt clean jvm/coverage jvm/test`

```
java.io.FileNotFoundException: /home/fommil/Projects/kerbal-calculator/jvm/target/scala-2.11/scoverage-report/home/fommil/Projects/kerbal-calculator/jvm/../shared/src/main/scala/com/github/fommil/kerbal/solver.scala.html (No such file or directory)
```

I suspect the problem might be due to the addition of relative unmanaged source paths.

**Comment by fommil** [comment]
oh, hold on, I think this is because the jvm/coverage task is never actually building anything. Hmm.

**Comment by sksamuel** [comment]
1.0.0+ uses the standard sbt build now, rather than a custom config so it should be picking up all your sources that a regular compile would.

**Comment by fommil** [comment]
Something is busticated. I'll link you when I push the project to github in a few moments.

**Comment by fommil** [comment]
https://github.com/fommil/kerbal-calculator

**Comment by fommil** [comment]
I've backed out the scoverage plugins for now

**Comment by sksamuel** [comment]
Yeah seen. Let me looksee

**Comment by sksamuel** [comment]
Deffo broken but I need to sit down and figure out how scalajs works.

**Comment by fommil** [comment]
the jvm module should be pure scala.
