### ISSUE TITLE
Can I use "sbt clean coverage test assembly"  to get a clean package?

### ISSUE THREAD

**Issue by clockfly** [scoverage/sbt-scoverage#83]
How codecov work?

Will it modify the intermediate class files? Can I use "sbt clean coverage test assembly"  to get a clean assembly package?

**Comment by clockfly** [comment]
Will post this in user group.

**Comment by gslowikowski** [comment]
User group thread https://groups.google.com/forum/#!topic/scala-code-coverage-tool/gxv8ZNgxZXs

I've tested ``sbt assembly publishLocal`` (without ``coverage`` command) on https://github.com/intel-hadoop/gearpump/tree/master/project project and generated ``pom.xml`` files still contain:
```xml
        <dependency>
            <groupId>org.scoverage</groupId>
            <artifactId>scalac-scoverage-runtime_2.11</artifactId>
            <version>1.0.1</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.scoverage</groupId>
            <artifactId>scalac-scoverage-plugin_2.11</artifactId>
            <version>1.0.1</version>
            <scope>provided</scope>
        </dependency>
```

The code https://github.com/scoverage/sbt-scoverage/blob/master/src/main/scala/scoverage/ScoverageSbtPlugin.scala#L93 is responsible for this problem.

**Comment by sksamuel** [comment]
@clockfly No, you must have two separate jobs. The modified class files are written out and used by the test cycle. So don't run assembly with the coverage.
