### ISSUE TITLE
Make postTestReport accessible

### ISSUE THREAD

**Issue by rozza** [scoverage/sbt-scoverage#88]
So I can set on custom test settings.

**Comment by rozza** [comment]
Currently working round by using all the default `testOptions in Test` and then overriding eg:

    testOptions in UnitTest <<= testOptions in Test
  
But it would be much nicer to do:

    testOptions in UnitTest <+= postTestReport

**Comment by ckipp01** [comment]
Seeing the age on this and the amount of changes that has happened since this was originally report, I'm going to go ahead and close. Please do comment back if this is still something relevant to you.
