### ISSUE TITLE
don't use absolute paths

### ISSUE THREAD

**Issue by fommil** [scoverage/sbt-scoverage#91]
I tried to copy the HTML report and put it on a webserver, but the drill down links didn't work because the file names were all absolute :disappointed:

**Comment by sksamuel** [comment]
You didn't copy your entire filessystem onto the web server?

It shouldn't be absolute, at least not on purpose.

**Comment by fommil** [comment]
hmm, it's a bit weirder than that... it looks like my absolute pathname is included in the `scoverage-report` directory (I've done a `coverageAggregate`) AND the links to drilldowns use full paths.

So actually, the absolute filenames is purely cosmetic, but the links in the HTML need to be relative rather than absolute on the webserver.

**Comment by gslowikowski** [comment]
As @sksamuel wrote, absolute paths are not on purpose. We need more details about your project to help you.

**Comment by fommil** [comment]
it's simple... just don't put a leading `/` in the anchor links in the output HTML.

**Comment by RichardBradley** [comment]
> > As @sksamuel wrote, absolute paths are not on purpose. We need more details about your project to help you.
> 
> it's simple... just don't put a leading / in the anchor links in the output HTML.

I can't reproduce this issue:

    $ grep 'href="/' -r target/scala-2.11/scoverage-report/
    $ grep 'href=/' -r target/scala-2.11/scoverage-report/

All the links in my scoverage reports are relative links. (Using ver 1.3.1)
