### ISSUE TITLE
The Activator Java project classes are not checked 

### ISSUE THREAD

**Issue by ykryshchuk** [scoverage/sbt-scoverage#95]
Hi,

I have a project that contains Java sources.

That is when I build the project the classes are compiled into "target/scala-2.11/classes". This contains everything compiled (java + scala).
I have another directory there - "target/scala-2.11/classes_managed", which contains only the Reverse* classes and views, actually these are the compiled scalas.

When I run coverage, it seems that only the "managed" classes are taken into account as I see in report only the classes mentioned in that directory, but my Java classes are ignored.

Is there a way to specify for plugin to use that first location as bytecode source so that my Java classes are inspected?

Thank you

**Comment by gslowikowski** [comment]
The rule is simple, only Scala classes are instrumented and taken into account in coverage calculation.

You have Play! Java project, so the only Scala sources are the ones generated from Play! templates and routes. If you've had Play! Scala project all your sources and generated sources would be instrumented.

**Comment by ykryshchuk** [comment]
:) that is why I post this issue.

would it be possible to extend the plugin with some parameter to specify what to instrument? e.g. only scala or scala + java etc

**Comment by gslowikowski** [comment]
No, it's not possible.
You can try Cobertura (https://bitbucket.org/jmhofer/cobertura4sbt/wiki/Home) or JaCoCo (https://bitbucket.org/jmhofer/jacoco4sbt, https://github.com/sbt/jacoco4sbt) for Java code coverage.

**Comment by sksamuel** [comment]
Closing this as its not feasible to have a single tool covering both scala and java - at least not in the way scoverage works. Maybe at the bytecode level, but then you run into issues in that.
