### ISSUE TITLE
Can not disable ScoverageSbtPlugin in a multi-project build

### ISSUE THREAD

**Issue by jeffreyolchovy** [scoverage/sbt-scoverage#96]
Given a trivial multi-project definition such as:

``` scala
import sbt._
import Keys._
import scoverage.ScoverageSbtPlugin

object MyProject extends Build {

  lazy val root = (project in file(".")).aggregate(common, reports, labs)

  lazy val common = (project in file("common"))

  lazy val reports = (project in file("reports")).dependsOn(common)

  lazy val labs = (project in file("labs")).dependsOn(reports).disablePlugins(ScoverageSbtPlugin)
}
```

The following error will be thrown at sbt startup:

```
sbt.AutoPluginException: Error determining plugins for project 'labs' in /projects/foo-scoverage/labs:
Contradiction in selected plugins.  These plugins were both included and excluded: scoverage.ScoverageSbtPlugin
    at sbt.AutoPluginException.withPrefix(Plugins.scala:108)
    at sbt.Load$.sbt$Load$$translateAutoPluginException(Load.scala:490)
    at sbt.Load$$anonfun$loadForProjects$1$1.apply(Load.scala:467)
    at sbt.Load$$anonfun$loadForProjects$1$1.apply(Load.scala:465)
    ...
    at xsbt.boot.Boot$.runImpl(Boot.scala:44)
    at xsbt.boot.Boot$.main(Boot.scala:20)
    at xsbt.boot.Boot.main(Boot.scala)
[error] sbt.AutoPluginException: Error determining plugins for project 'labs' in /projects/foo-scoverage/labs:
[error] Contradiction in selected plugins.  These plugins were both included and excluded: scoverage.ScoverageSbtPlugin
```

I consider this an issue since this is the advertised way of disabling an AutoPlugin, according to sbt documentation (http://www.scala-sbt.org/0.13/docs/Plugins.html#Using+an+auto+plugin). Though, in general, I'd like to know if it's currently possible to disable Scoverage for particular projects in a multi-project build by any other means.

**Comment by fommil** [comment]
I'd also like to disable instrumentation/reports for submodules. As a workaround, I do this

```scala
[some submodule].settings(
    ScoverageKeys.coverageExcludedPackages := ".*"
  )
```

**Comment by yardena** [comment]
+1

**Comment by myyk** [comment]
I'm having a similar problem with another AutoPlugin that is has no requirements when I have subprojects. It seems to be an issue with sbt possibly related to this: https://github.com/sbt/sbt/issues/1926

**Comment by jeffreyolchovy** [comment]
@myyk yep, sounds like it. thanks for the notice.

**Comment by jeffmay** [comment]
+1

**Comment by alexandru** [comment]
:+1:

**Comment by edmondo1984** [comment]
Is this fixed? I get the unfamous symmetric/asymmetric tree problem on 2.11.8 and I am not able to disable the plugin on a submodule where I don't really need it. As a consequence I had to disable coverage completely

**Comment by alexandru** [comment]
@edmondo1984 personally I worked around it by using an SBT "profile", only enabling it when `-Dsbt.profile=coverage` is passed as a command-line option to SBT.

If you're interested in details, see https://github.com/monix/monix/blob/master/build.sbt

**Comment by edmondo1984** [comment]
I need to disable the plugib a single module in a multi module would that
work?

On 17 Dec 2016 7:25 a.m., "Alexandru Nedelcu" <notifications@github.com>
wrote:

@edmondo1984 <https://github.com/edmondo1984> personally I worked around it
by using an SBT "profile", only enabling it when -Dsbt.profile=coverage is
passed as a command-line option to SBT.

If you're interested in details, see https://github.com/monix/
monix/blob/master/build.sbt

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/scoverage/sbt-scoverage/issues/96#issuecomment-267746329>,
or mute the thread

**Comment by gslowikowski** [comment]
Add `coverageEnabled := false` to module settings.

**Comment by ckipp01** [comment]
So testing this again (5 years later) it does seem that `disablePlugins(ScoverageSbtPlugin)` does work as expected. Unsure if it was fixed upstream or not. Pair that with the possibility of using `coverageEnabled := false`, I'm going to go ahead and close.
